/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_STATUS_ENTITIES_ENGINEREMOTESTART_ERSSTATUS_PB_H_INCLUDED
#define PB_STATUS_ENTITIES_ENGINEREMOTESTART_ERSSTATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _status_ErsStatusType { 
    status_ErsStatusType_ERS_STATUS_OFF = 0, 
    status_ErsStatusType_ERS_STATUS_STARTING = 1, 
    status_ErsStatusType_ERS_STATUS_RUNNING = 2 
} status_ErsStatusType;

typedef enum _status_ErsStartResultType { 
    status_ErsStartResultType_ERS_START_RESULT_NOT_SET = 0, 
    status_ErsStartResultType_ERS_START_RESULT_SUCCESS = 1, 
    status_ErsStartResultType_ERS_START_RESULT_INH_MAX_NOT_START = 2, 
    status_ErsStartResultType_ERS_START_RESULT_INH_CAR_UNLOCKED = 3, 
    status_ErsStartResultType_ERS_START_RESULT_INH_KEY_IN_CAR = 4, 
    status_ErsStartResultType_ERS_START_RESULT_INH_DOOR_OPEN = 5, 
    status_ErsStartResultType_ERS_START_RESULT_INH_HOOD_OPEN = 6, 
    status_ErsStartResultType_ERS_START_RESULT_INH_GEAR_NOT_P = 7, 
    status_ErsStartResultType_ERS_START_RESULT_INH_USER_IN_CAR = 8, 
    status_ErsStartResultType_ERS_START_RESULT_INH_PEDAL_PRESSED = 9, 
    status_ErsStartResultType_ERS_START_RESULT_INH_LO_FUEL = 10, 
    status_ErsStartResultType_ERS_START_RESULT_INH_LO_BATT = 11, 
    status_ErsStartResultType_ERS_START_RESULT_INH_ENG_COOLANT = 12, 
    status_ErsStartResultType_ERS_START_RESULT_INH_ENG_FAULT = 13, 
    status_ErsStartResultType_ERS_START_RESULT_INH_OTHER = 14, 
    status_ErsStartResultType_ERS_START_RESULT_ABORT_ENG_FAULT = 15, 
    status_ErsStartResultType_ERS_START_RESULT_ABORT_ENG_COOLANT = 16, 
    status_ErsStartResultType_ERS_START_RESULT_ABORT_LO_FUEL = 17, 
    status_ErsStartResultType_ERS_START_RESULT_ABORT_LO_BATT = 18, 
    status_ErsStartResultType_ERS_START_RESULT_ABORT_OTHER = 19 
} status_ErsStartResultType;

/* Struct definitions */
typedef struct _status_ErsStatus { 
    status_ErsStatusType status; 
    status_ErsStartResultType start_result; 
} status_ErsStatus;


/* Helper constants for enums */
#define _status_ErsStatusType_MIN status_ErsStatusType_ERS_STATUS_OFF
#define _status_ErsStatusType_MAX status_ErsStatusType_ERS_STATUS_RUNNING
#define _status_ErsStatusType_ARRAYSIZE ((status_ErsStatusType)(status_ErsStatusType_ERS_STATUS_RUNNING+1))

#define _status_ErsStartResultType_MIN status_ErsStartResultType_ERS_START_RESULT_NOT_SET
#define _status_ErsStartResultType_MAX status_ErsStartResultType_ERS_START_RESULT_ABORT_OTHER
#define _status_ErsStartResultType_ARRAYSIZE ((status_ErsStartResultType)(status_ErsStartResultType_ERS_START_RESULT_ABORT_OTHER+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define status_ErsStatus_init_default            {_status_ErsStatusType_MIN, _status_ErsStartResultType_MIN}
#define status_ErsStatus_init_zero               {_status_ErsStatusType_MIN, _status_ErsStartResultType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define status_ErsStatus_status_tag              1
#define status_ErsStatus_start_result_tag        2

/* Struct field encoding specification for nanopb */
#define status_ErsStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, UENUM,    start_result,      2)
#define status_ErsStatus_CALLBACK NULL
#define status_ErsStatus_DEFAULT NULL

extern const pb_msgdesc_t status_ErsStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define status_ErsStatus_fields &status_ErsStatus_msg

/* Maximum encoded size of messages (where known) */
#define status_ErsStatus_size                    4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
