/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_OTA_GETOTAINSTALLATIONSTATUSRESPONSE_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_OTA_GETOTAINSTALLATIONSTATUSRESPONSE_PB_H_INCLUDED
#include <pb.h>
#include "entities/common/ResponseStatus.pb.h"
#include "entities/otamode/OTAInstallationStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* OID {1.3.6.1.4.1.37916.3.6.12.2.1.3} */
typedef struct _remote_control_GetOTAInstallationStatusResponse { 
    bool has_response_status;
    common_ResponseStatus response_status; /* required */
    bool has_ota_status;
    status_OTAInstallationStatus ota_status; 
} remote_control_GetOTAInstallationStatusResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_GetOTAInstallationStatusResponse_init_default {false, common_ResponseStatus_init_default, false, status_OTAInstallationStatus_init_default}
#define remote_control_GetOTAInstallationStatusResponse_init_zero {false, common_ResponseStatus_init_zero, false, status_OTAInstallationStatus_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_GetOTAInstallationStatusResponse_response_status_tag 1
#define remote_control_GetOTAInstallationStatusResponse_ota_status_tag 2

/* Struct field encoding specification for nanopb */
#define remote_control_GetOTAInstallationStatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  response_status,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ota_status,        2)
#define remote_control_GetOTAInstallationStatusResponse_CALLBACK NULL
#define remote_control_GetOTAInstallationStatusResponse_DEFAULT NULL
#define remote_control_GetOTAInstallationStatusResponse_response_status_MSGTYPE common_ResponseStatus
#define remote_control_GetOTAInstallationStatusResponse_ota_status_MSGTYPE status_OTAInstallationStatus

extern const pb_msgdesc_t remote_control_GetOTAInstallationStatusResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_GetOTAInstallationStatusResponse_fields &remote_control_GetOTAInstallationStatusResponse_msg

/* Maximum encoded size of messages (where known) */
#if defined(common_ResponseStatus_size)
#define remote_control_GetOTAInstallationStatusResponse_size (10 + common_ResponseStatus_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
