/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_OTA_OTAINSTALLATIONSTATUSUPDATE_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_OTA_OTAINSTALLATIONSTATUSUPDATE_PB_H_INCLUDED
#include <pb.h>
#include "entities/otamode/OTAInstallationStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* OID {1.3.6.1.4.1.37916.3.6.12.2.0.1} */
typedef struct _remote_control_OTAInstallationStatusUpdate { 
    bool has_ota_status;
    status_OTAInstallationStatus ota_status; 
} remote_control_OTAInstallationStatusUpdate;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_OTAInstallationStatusUpdate_init_default {false, status_OTAInstallationStatus_init_default}
#define remote_control_OTAInstallationStatusUpdate_init_zero {false, status_OTAInstallationStatus_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_OTAInstallationStatusUpdate_ota_status_tag 1

/* Struct field encoding specification for nanopb */
#define remote_control_OTAInstallationStatusUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ota_status,        1)
#define remote_control_OTAInstallationStatusUpdate_CALLBACK NULL
#define remote_control_OTAInstallationStatusUpdate_DEFAULT NULL
#define remote_control_OTAInstallationStatusUpdate_ota_status_MSGTYPE status_OTAInstallationStatus

extern const pb_msgdesc_t remote_control_OTAInstallationStatusUpdate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_OTAInstallationStatusUpdate_fields &remote_control_OTAInstallationStatusUpdate_msg

/* Maximum encoded size of messages (where known) */
#define remote_control_OTAInstallationStatusUpdate_size 4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
