<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ComponentModels\FightSequenceModel.cs~RF28cf19c3.TMP" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SeedData\demo-baron-aldric.json">
      <LogicalName>DA_Models.SeedData.demo-baron-aldric.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DA_Common\DA_Common.csproj" />
    <ProjectReference Include="..\DA_DataAccess\DA_DataAccess.csproj" />
  </ItemGroup>

</Project>
