/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_CARTIMEOFFSET_CARTIMEOFFSETUPDATE_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_CARTIMEOFFSET_CARTIMEOFFSETUPDATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _remote_control_CarTimeOffsetUpdate {
    int32_t offset_minutes; /* Time difference between in-car clock and UTC in minutes */
} remote_control_CarTimeOffsetUpdate;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_CarTimeOffsetUpdate_init_default {0}
#define remote_control_CarTimeOffsetUpdate_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_CarTimeOffsetUpdate_offset_minutes_tag 1

/* Struct field encoding specification for nanopb */
#define remote_control_CarTimeOffsetUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    offset_minutes,    1)
#define remote_control_CarTimeOffsetUpdate_CALLBACK NULL
#define remote_control_CarTimeOffsetUpdate_DEFAULT NULL

extern const pb_msgdesc_t remote_control_CarTimeOffsetUpdate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_CarTimeOffsetUpdate_fields &remote_control_CarTimeOffsetUpdate_msg

/* Maximum encoded size of messages (where known) */
#define remote_control_CarTimeOffsetUpdate_size  11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif