/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_MESSAGES_IHUTIMEOFFSET_IHU_TIME_OFFSET_PB_H_INCLUDED
#define PB_MESSAGES_IHUTIMEOFFSET_IHU_TIME_OFFSET_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* SOME/IP service: 0xA831, TCP-Port: 30552, Method: 0x0501
 IHU requests TCAM to schedule a wake-up after a specified duration */
typedef struct _ScheduleWakeup {
    uint32_t minutes_until_wakeup; /* Duration in minutes */
    int32_t seconds_until_wakeup; /* Duration in seconds until IHU wants to be woken up, or -1 to cancel the wake-up timer (used when timezone does not support DST) */
} ScheduleWakeup;

typedef struct _ScheduleWakeupResponse {
    bool success; /* Request was successful */
} ScheduleWakeupResponse;

/* SOME/IP service: 0xA831, TCP-Port: 30552, Method: 0x0502
 IHU sends its current local time to TCAM so TCAM can calculate the IHU clock offset from actual UTC time */
typedef struct _SetIhuTime {
    int64_t seconds_since_epoch_local; /* Number of seconds since 1970-01-01 00:00:00 in IHU's local time */
} SetIhuTime;

typedef struct _SetIhuTimeResponse {
    bool success; /* Request was successful */
} SetIhuTimeResponse;

/* SOME/IP service: 0xA831, TCP-Port: 30552, Method: 0x0500
 Deprecated: Use SetIhuTime instead */
typedef struct _SetTimezoneOffset {
    int32_t offset_in_minutes; /* Offset of cartime from UTC in minutes (deprecated) */
} SetTimezoneOffset;

typedef struct _SetTimezoneOffsetResponse {
    bool success; /* Request was successful */
} SetTimezoneOffsetResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SetTimezoneOffset_init_default           {0}
#define SetTimezoneOffsetResponse_init_default   {0}
#define ScheduleWakeup_init_default              {0, 0}
#define ScheduleWakeupResponse_init_default      {0}
#define SetIhuTime_init_default                  {0}
#define SetIhuTimeResponse_init_default          {0}
#define SetTimezoneOffset_init_zero              {0}
#define SetTimezoneOffsetResponse_init_zero      {0}
#define ScheduleWakeup_init_zero                 {0, 0}
#define ScheduleWakeupResponse_init_zero         {0}
#define SetIhuTime_init_zero                     {0}
#define SetIhuTimeResponse_init_zero             {0}

/* Field tags (for use in manual encoding/decoding) */
#define ScheduleWakeup_minutes_until_wakeup_tag  1
#define ScheduleWakeup_seconds_until_wakeup_tag  2
#define ScheduleWakeupResponse_success_tag       1
#define SetIhuTime_seconds_since_epoch_local_tag 1
#define SetIhuTimeResponse_success_tag           1
#define SetTimezoneOffset_offset_in_minutes_tag  1
#define SetTimezoneOffsetResponse_success_tag    1

/* Struct field encoding specification for nanopb */
#define SetTimezoneOffset_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   offset_in_minutes,   1)
#define SetTimezoneOffset_CALLBACK NULL
#define SetTimezoneOffset_DEFAULT NULL

#define SetTimezoneOffsetResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define SetTimezoneOffsetResponse_CALLBACK NULL
#define SetTimezoneOffsetResponse_DEFAULT NULL

#define ScheduleWakeup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   minutes_until_wakeup,   1) \
X(a, STATIC,   SINGULAR, INT32,    seconds_until_wakeup,   2)
#define ScheduleWakeup_CALLBACK NULL
#define ScheduleWakeup_DEFAULT NULL

#define ScheduleWakeupResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define ScheduleWakeupResponse_CALLBACK NULL
#define ScheduleWakeupResponse_DEFAULT NULL

#define SetIhuTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    seconds_since_epoch_local,   1)
#define SetIhuTime_CALLBACK NULL
#define SetIhuTime_DEFAULT NULL

#define SetIhuTimeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define SetIhuTimeResponse_CALLBACK NULL
#define SetIhuTimeResponse_DEFAULT NULL

extern const pb_msgdesc_t SetTimezoneOffset_msg;
extern const pb_msgdesc_t SetTimezoneOffsetResponse_msg;
extern const pb_msgdesc_t ScheduleWakeup_msg;
extern const pb_msgdesc_t ScheduleWakeupResponse_msg;
extern const pb_msgdesc_t SetIhuTime_msg;
extern const pb_msgdesc_t SetIhuTimeResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SetTimezoneOffset_fields &SetTimezoneOffset_msg
#define SetTimezoneOffsetResponse_fields &SetTimezoneOffsetResponse_msg
#define ScheduleWakeup_fields &ScheduleWakeup_msg
#define ScheduleWakeupResponse_fields &ScheduleWakeupResponse_msg
#define SetIhuTime_fields &SetIhuTime_msg
#define SetIhuTimeResponse_fields &SetIhuTimeResponse_msg

/* Maximum encoded size of messages (where known) */
#define ScheduleWakeupResponse_size              2
#define ScheduleWakeup_size                      17
#define SetIhuTimeResponse_size                  2
#define SetIhuTime_size                          11
#define SetTimezoneOffsetResponse_size           2
#define SetTimezoneOffset_size                   6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif