/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_BATTERYCHARGE_CHARGECONTROLSTATUSUPDATE_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_BATTERYCHARGE_CHARGECONTROLSTATUSUPDATE_PB_H_INCLUDED
#include <pb.h>
#include "entities/batterycharge/ChargeControlStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* OID {1.3.6.1.4.1.37916.3.6.21.7.3.1} */
typedef struct _remote_control_ChargeControlStatusUpdate { 
    remote_control_ChargeControlStatus charge_control_status; 
    uint32_t amp_limit; /* / Currently used amp limit towards OBC, might differ from location setting if optimizer has lowered it */
} remote_control_ChargeControlStatusUpdate;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_ChargeControlStatusUpdate_init_default {_remote_control_ChargeControlStatus_MIN, 0}
#define remote_control_ChargeControlStatusUpdate_init_zero {_remote_control_ChargeControlStatus_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_ChargeControlStatusUpdate_charge_control_status_tag 1
#define remote_control_ChargeControlStatusUpdate_amp_limit_tag 2

/* Struct field encoding specification for nanopb */
#define remote_control_ChargeControlStatusUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    charge_control_status,   1) \
X(a, STATIC,   SINGULAR, UINT32,   amp_limit,         2)
#define remote_control_ChargeControlStatusUpdate_CALLBACK NULL
#define remote_control_ChargeControlStatusUpdate_DEFAULT NULL

extern const pb_msgdesc_t remote_control_ChargeControlStatusUpdate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_ChargeControlStatusUpdate_fields &remote_control_ChargeControlStatusUpdate_msg

/* Maximum encoded size of messages (where known) */
#define remote_control_ChargeControlStatusUpdate_size 8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
