/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_ICUP_CHARGING_MESSAGES_BATTERYCHARGE_ICUP_CHARGING_PB_H_INCLUDED
#define PB_ICUP_CHARGING_MESSAGES_BATTERYCHARGE_ICUP_CHARGING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _icup_charging_ChargeControlStatus { 
    icup_charging_ChargeControlStatus_CHARGE_CONTROL_STATUS_UNSPECIFIED = 0, 
    icup_charging_ChargeControlStatus_CHARGE_CONTROL_STATUS_CHARGING_TOWARDS_MIN_SOC = 1, 
    icup_charging_ChargeControlStatus_CHARGE_CONTROL_STATUS_MANUAL_PLUG_IN_CHARGING = 2, 
    icup_charging_ChargeControlStatus_CHARGE_CONTROL_STATUS_MANUAL_SCHEDULE_CHARGING = 3, 
    icup_charging_ChargeControlStatus_CHARGE_CONTROL_STATUS_SMART_CHARGING = 4, 
    icup_charging_ChargeControlStatus_CHARGE_CONTROL_STATUS_CHARGE_NOW = 5 
} icup_charging_ChargeControlStatus;

/* Daily is 90%. Long Trip is 100%. Custom means that the user sets their own value. */
typedef enum _icup_charging_TargetSocSetting { 
    icup_charging_TargetSocSetting_TARGET_SOC_SETTING_UNSPECIFIED = 0, 
    icup_charging_TargetSocSetting_TARGET_SOC_SETTING_DAILY = 1, 
    icup_charging_TargetSocSetting_TARGET_SOC_SETTING_LONG_TRIP = 2, 
    icup_charging_TargetSocSetting_TARGET_SOC_SETTING_CUSTOM = 3 
} icup_charging_TargetSocSetting;

typedef enum _icup_charging_ScheduleType { 
    icup_charging_ScheduleType_SCHEDULE_TYPE_UNSPECIFIED = 0, /* Default */
    icup_charging_ScheduleType_SCHEDULE_TYPE_NONE = 1, /* No schedule should be used */
    icup_charging_ScheduleType_SCHEDULE_TYPE_MANUAL_SCHEDULE = 2, /* Manual schedule should be used */
    icup_charging_ScheduleType_SCHEDULE_TYPE_DEPARTURE_TIME = 3 /* Smart Charging departure time should be used */
} icup_charging_ScheduleType;

/* Struct definitions */
typedef struct _icup_charging_ActiveDays { 
    bool monday; 
    bool tuesday; 
    bool wednesday; 
    bool thursday; 
    bool friday; 
    bool saturday; 
    bool sunday; 
} icup_charging_ActiveDays;

/* SomeIp service: 0xA829, event: 0x8004 */
typedef struct _icup_charging_ChargeControlStatusUpdate { 
    icup_charging_ChargeControlStatus charge_control_status; 
    uint32_t amp_limit; /* Might differ from location setting as optimizer can lower it during periods */
} icup_charging_ChargeControlStatusUpdate;

/* SomeIp service: 0xA829, event: 0x8005 */
typedef struct _icup_charging_ChargingLocationDeletedUpdate { 
    char uuid[37]; /* Location uuid of deleted location */
} icup_charging_ChargingLocationDeletedUpdate;

/* SomeIp service: 0xA829, method: 0x0500 */
typedef struct _icup_charging_CreateChargingLocationResponse { 
    char uuid[37]; /* Location uuid */
} icup_charging_CreateChargingLocationResponse;

/* SomeIp service: 0xA829, method: 0x0502
 The response's payload is one dummy byte that has no meaning and can be ignored. */
typedef struct _icup_charging_DeleteChargingLocationRequest { 
    char uuid[37]; /* Uuid of location to remove */
} icup_charging_DeleteChargingLocationRequest;

/* SomeIp service: 0xA829, method: 0x0505
 The request's payload will be ignored, and can be a single dummy-byte. */
typedef struct _icup_charging_GetChargeNowResponse { 
    bool charge_now; /* ChargeNow On/Off */
} icup_charging_GetChargeNowResponse;

/* SomeIp service: 0xA829, method: 0x0507
 The request's payload will be ignored, and can be a single dummy-byte.
 Note that if the setting is not custom, `target_soc` will have the pre-set value for the respective setting. */
typedef struct _icup_charging_GetTargetSocResponse { 
    uint32_t target_soc; /* Percent - valid values are 0-100. */
    icup_charging_TargetSocSetting setting; 
} icup_charging_GetTargetSocResponse;

typedef struct _icup_charging_Position { 
    double latitude; 
    double longitude; 
} icup_charging_Position;

/* SomeIp service: 0xA829, method: 0x0504
 The response's payload is one dummy byte that has no meaning and can be ignored. */
typedef struct _icup_charging_SetChargeNowRequest { 
    bool charge_now; /* ChargeNow On/Off */
} icup_charging_SetChargeNowRequest;

/* SomeIp service: 0xA829, method: 0x0506
 The response's payload is one dummy byte that has no meaning and can be ignored. */
typedef struct _icup_charging_SetTargetSocRequest { 
    uint32_t target_soc; /* Percent - valid values are 0-100. This value is ignored if setting is not Custom. */
    icup_charging_TargetSocSetting setting; 
} icup_charging_SetTargetSocRequest;

/* SomeIp service: 0xA829, event group: 0x01, event: 0x8006
 Note that if the setting is not custom, `target_soc` will have the pre-set value for the respective setting. */
typedef struct _icup_charging_TargetSocUpdate { 
    uint32_t target_soc; /* Percent - valid values are 0-100. */
    icup_charging_TargetSocSetting setting; 
} icup_charging_TargetSocUpdate;

typedef struct _icup_charging_DepartureTime { 
    bool active; /* Is the schedule active. Used to toggle on/off */
    uint32_t time; /* Time in minutes from midnight (unqualified) */
    bool has_active_days;
    icup_charging_ActiveDays active_days; /* Which days should the schedule be active */
} icup_charging_DepartureTime;

typedef struct _icup_charging_ManualSchedule { 
    bool active; /* Is the schedule active. Used to toggle on/off */
    uint32_t start_time; /* Time in minutes from midnight (unqualified) */
    uint32_t end_time; /* Time in minutes from midnight (unqualified) */
    bool has_active_days;
    icup_charging_ActiveDays active_days; /* Which days should the schedule be active */
} icup_charging_ManualSchedule;

typedef struct _icup_charging_Schedule { 
    pb_size_t manual_schedule_count;
    icup_charging_ManualSchedule manual_schedule[7]; /* List of manual schedules. Maximum 7 schedules */
    pb_size_t departure_time_count;
    icup_charging_DepartureTime departure_time[7]; /* List of smart charging departure times. Maximum 7 departure times */
    icup_charging_ScheduleType active_schedule; /* Schedule type picker */
} icup_charging_Schedule;

/* SomeIp service: 0xA829, event: 0x8003 */
typedef struct _icup_charging_ChargingLocationActualUpdate { 
    char uuid[37]; /* Location uuid */
    char alias[129]; /* Location alias */
    bool has_position;
    icup_charging_Position position; /* Position of ChargingLocation */
    uint32_t amp_limit; /* Maximum charging current in ampere (6-48A) */
    uint32_t minimum_soc; /* Minimum state of charge in percent. If battery SOC is below limit then car will always charge */
    bool has_schedule;
    icup_charging_Schedule schedule; /* User schedules for this location */
    bool smart_charging_supported; /* Whether smart charging is supported at this location (will be true if location is onboarded for smart charging, controlled by cloud) */
} icup_charging_ChargingLocationActualUpdate;

/* SomeIp service: 0xA829, event: 0x8002 */
typedef struct _icup_charging_ChargingLocationDefaultUpdate { 
    char uuid[37]; /* Location uuid */
    char alias[129]; /* Location alias */
    bool has_position;
    icup_charging_Position position; /* Position of ChargingLocation */
    uint32_t amp_limit; /* Maximum charging current in ampere (6-48A) */
    uint32_t minimum_soc; /* Minimum state of charge in percent. If battery SOC is below limit then car will always charge */
    bool has_schedule;
    icup_charging_Schedule schedule; /* User schedules for this location */
} icup_charging_ChargingLocationDefaultUpdate;

/* SomeIp service: 0xA829, event: 0x8000 */
typedef struct _icup_charging_ChargingLocationUpdate { 
    char uuid[37]; /* Location uuid */
    char alias[129]; /* Location alias */
    bool has_position;
    icup_charging_Position position; /* Position of ChargingLocation */
    uint32_t amp_limit; /* Maximum charging current in ampere (6-48A) */
    uint32_t minimum_soc; /* Minimum state of charge in percent. If battery SOC is below limit then car will always charge */
    bool has_schedule;
    icup_charging_Schedule schedule; /* User schedules for this location */
    bool smart_charging_supported; /* Whether smart charging is supported at this location (will be true if location is onboarded for smart charging, controlled by cloud) */
} icup_charging_ChargingLocationUpdate;

/* SomeIp service: 0xA829, method: 0x0500 */
typedef struct _icup_charging_CreateChargingLocationRequest { 
    char alias[129]; /* Location alias */
    bool has_position;
    icup_charging_Position position; /* Position of ChargingLocation */
    uint32_t amp_limit; /* Maximum charging current in ampere (6-48A) */
    uint32_t minimum_soc; /* Minimum state of charge in percent. If battery SOC is below limit then car will always charge */
    bool has_schedule;
    icup_charging_Schedule schedule; /* User schedules for this location */
    bool smart_charging_supported; /* Whether smart charging is supported at this location (currently IHU cannot control this and value will be ignored) */
} icup_charging_CreateChargingLocationRequest;

/* SomeIp service: 0xA829, method: 0x0501
 The response's payload is one dummy byte that has no meaning and can be ignored. */
typedef struct _icup_charging_ModifyChargingLocationRequest { 
    char uuid[37]; /* Location uuid */
    char alias[129]; /* Location alias */
    bool has_position;
    icup_charging_Position position; /* Position of ChargingLocation */
    uint32_t amp_limit; /* Maximum charging current in ampere (6-48A) */
    uint32_t minimum_soc; /* Minimum state of charge in percent. If battery SOC is below limit then car will always charge */
    bool has_schedule;
    icup_charging_Schedule schedule; /* User schedules for this location */
    bool smart_charging_supported; /* Whether smart charging is supported at this location (currently IHU cannot control this and value will be ignored) */
} icup_charging_ModifyChargingLocationRequest;

/* SomeIp service: 0xA829, event: TBD */
typedef struct _icup_charging_CurrentChargingSettingsUpdate { 
    uint32_t charging_controller_status; /* Current status of charging controller. TODO PB enum? */
    bool has_current_location;
    icup_charging_ChargingLocationUpdate current_location; /* Current charging location. */
    uint32_t target_soc; /* Target SOC, if not controlled by location, global will be used */
    uint32_t upcoming_schedule_start_time; /* Time in minutes from midnight (unqualified). TODO represent day needed? */
    uint32_t upcoming_schedule_end_time; /* Time in minutes from midnight (unqualified) */
} icup_charging_CurrentChargingSettingsUpdate;

/* SomeIp service: 0xA829, method: 0x0503
 The request's payload will be ignored, and can be a single dummy-byte. */
typedef struct _icup_charging_GetAllChargingLocationsResponse { 
    bool has_default_location;
    icup_charging_ChargingLocationDefaultUpdate default_location; 
    bool has_actual_location;
    icup_charging_ChargingLocationActualUpdate actual_location; 
    pb_size_t locations_count;
    icup_charging_ChargingLocationUpdate locations[20]; 
} icup_charging_GetAllChargingLocationsResponse;


/* Helper constants for enums */
#define _icup_charging_ChargeControlStatus_MIN icup_charging_ChargeControlStatus_CHARGE_CONTROL_STATUS_UNSPECIFIED
#define _icup_charging_ChargeControlStatus_MAX icup_charging_ChargeControlStatus_CHARGE_CONTROL_STATUS_CHARGE_NOW
#define _icup_charging_ChargeControlStatus_ARRAYSIZE ((icup_charging_ChargeControlStatus)(icup_charging_ChargeControlStatus_CHARGE_CONTROL_STATUS_CHARGE_NOW+1))

#define _icup_charging_TargetSocSetting_MIN icup_charging_TargetSocSetting_TARGET_SOC_SETTING_UNSPECIFIED
#define _icup_charging_TargetSocSetting_MAX icup_charging_TargetSocSetting_TARGET_SOC_SETTING_CUSTOM
#define _icup_charging_TargetSocSetting_ARRAYSIZE ((icup_charging_TargetSocSetting)(icup_charging_TargetSocSetting_TARGET_SOC_SETTING_CUSTOM+1))

#define _icup_charging_ScheduleType_MIN icup_charging_ScheduleType_SCHEDULE_TYPE_UNSPECIFIED
#define _icup_charging_ScheduleType_MAX icup_charging_ScheduleType_SCHEDULE_TYPE_DEPARTURE_TIME
#define _icup_charging_ScheduleType_ARRAYSIZE ((icup_charging_ScheduleType)(icup_charging_ScheduleType_SCHEDULE_TYPE_DEPARTURE_TIME+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define icup_charging_ActiveDays_init_default    {0, 0, 0, 0, 0, 0, 0}
#define icup_charging_ManualSchedule_init_default {0, 0, 0, false, icup_charging_ActiveDays_init_default}
#define icup_charging_DepartureTime_init_default {0, 0, false, icup_charging_ActiveDays_init_default}
#define icup_charging_Schedule_init_default      {0, {icup_charging_ManualSchedule_init_default, icup_charging_ManualSchedule_init_default, icup_charging_ManualSchedule_init_default, icup_charging_ManualSchedule_init_default, icup_charging_ManualSchedule_init_default, icup_charging_ManualSchedule_init_default, icup_charging_ManualSchedule_init_default}, 0, {icup_charging_DepartureTime_init_default, icup_charging_DepartureTime_init_default, icup_charging_DepartureTime_init_default, icup_charging_DepartureTime_init_default, icup_charging_DepartureTime_init_default, icup_charging_DepartureTime_init_default, icup_charging_DepartureTime_init_default}, _icup_charging_ScheduleType_MIN}
#define icup_charging_Position_init_default      {0, 0}
#define icup_charging_SetTargetSocRequest_init_default {0, _icup_charging_TargetSocSetting_MIN}
#define icup_charging_GetTargetSocResponse_init_default {0, _icup_charging_TargetSocSetting_MIN}
#define icup_charging_TargetSocUpdate_init_default {0, _icup_charging_TargetSocSetting_MIN}
#define icup_charging_ChargingLocationUpdate_init_default {"", "", false, icup_charging_Position_init_default, 0, 0, false, icup_charging_Schedule_init_default, 0}
#define icup_charging_CurrentChargingSettingsUpdate_init_default {0, false, icup_charging_ChargingLocationUpdate_init_default, 0, 0, 0}
#define icup_charging_ChargingLocationDefaultUpdate_init_default {"", "", false, icup_charging_Position_init_default, 0, 0, false, icup_charging_Schedule_init_default}
#define icup_charging_ChargingLocationActualUpdate_init_default {"", "", false, icup_charging_Position_init_default, 0, 0, false, icup_charging_Schedule_init_default, 0}
#define icup_charging_ChargeControlStatusUpdate_init_default {_icup_charging_ChargeControlStatus_MIN, 0}
#define icup_charging_CreateChargingLocationRequest_init_default {"", false, icup_charging_Position_init_default, 0, 0, false, icup_charging_Schedule_init_default, 0}
#define icup_charging_CreateChargingLocationResponse_init_default {""}
#define icup_charging_ModifyChargingLocationRequest_init_default {"", "", false, icup_charging_Position_init_default, 0, 0, false, icup_charging_Schedule_init_default, 0}
#define icup_charging_DeleteChargingLocationRequest_init_default {""}
#define icup_charging_ChargingLocationDeletedUpdate_init_default {""}
#define icup_charging_GetAllChargingLocationsResponse_init_default {false, icup_charging_ChargingLocationDefaultUpdate_init_default, false, icup_charging_ChargingLocationActualUpdate_init_default, 0, {icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default, icup_charging_ChargingLocationUpdate_init_default}}
#define icup_charging_SetChargeNowRequest_init_default {0}
#define icup_charging_GetChargeNowResponse_init_default {0}
#define icup_charging_ActiveDays_init_zero       {0, 0, 0, 0, 0, 0, 0}
#define icup_charging_ManualSchedule_init_zero   {0, 0, 0, false, icup_charging_ActiveDays_init_zero}
#define icup_charging_DepartureTime_init_zero    {0, 0, false, icup_charging_ActiveDays_init_zero}
#define icup_charging_Schedule_init_zero         {0, {icup_charging_ManualSchedule_init_zero, icup_charging_ManualSchedule_init_zero, icup_charging_ManualSchedule_init_zero, icup_charging_ManualSchedule_init_zero, icup_charging_ManualSchedule_init_zero, icup_charging_ManualSchedule_init_zero, icup_charging_ManualSchedule_init_zero}, 0, {icup_charging_DepartureTime_init_zero, icup_charging_DepartureTime_init_zero, icup_charging_DepartureTime_init_zero, icup_charging_DepartureTime_init_zero, icup_charging_DepartureTime_init_zero, icup_charging_DepartureTime_init_zero, icup_charging_DepartureTime_init_zero}, _icup_charging_ScheduleType_MIN}
#define icup_charging_Position_init_zero         {0, 0}
#define icup_charging_SetTargetSocRequest_init_zero {0, _icup_charging_TargetSocSetting_MIN}
#define icup_charging_GetTargetSocResponse_init_zero {0, _icup_charging_TargetSocSetting_MIN}
#define icup_charging_TargetSocUpdate_init_zero  {0, _icup_charging_TargetSocSetting_MIN}
#define icup_charging_ChargingLocationUpdate_init_zero {"", "", false, icup_charging_Position_init_zero, 0, 0, false, icup_charging_Schedule_init_zero, 0}
#define icup_charging_CurrentChargingSettingsUpdate_init_zero {0, false, icup_charging_ChargingLocationUpdate_init_zero, 0, 0, 0}
#define icup_charging_ChargingLocationDefaultUpdate_init_zero {"", "", false, icup_charging_Position_init_zero, 0, 0, false, icup_charging_Schedule_init_zero}
#define icup_charging_ChargingLocationActualUpdate_init_zero {"", "", false, icup_charging_Position_init_zero, 0, 0, false, icup_charging_Schedule_init_zero, 0}
#define icup_charging_ChargeControlStatusUpdate_init_zero {_icup_charging_ChargeControlStatus_MIN, 0}
#define icup_charging_CreateChargingLocationRequest_init_zero {"", false, icup_charging_Position_init_zero, 0, 0, false, icup_charging_Schedule_init_zero, 0}
#define icup_charging_CreateChargingLocationResponse_init_zero {""}
#define icup_charging_ModifyChargingLocationRequest_init_zero {"", "", false, icup_charging_Position_init_zero, 0, 0, false, icup_charging_Schedule_init_zero, 0}
#define icup_charging_DeleteChargingLocationRequest_init_zero {""}
#define icup_charging_ChargingLocationDeletedUpdate_init_zero {""}
#define icup_charging_GetAllChargingLocationsResponse_init_zero {false, icup_charging_ChargingLocationDefaultUpdate_init_zero, false, icup_charging_ChargingLocationActualUpdate_init_zero, 0, {icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero, icup_charging_ChargingLocationUpdate_init_zero}}
#define icup_charging_SetChargeNowRequest_init_zero {0}
#define icup_charging_GetChargeNowResponse_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define icup_charging_ActiveDays_monday_tag      1
#define icup_charging_ActiveDays_tuesday_tag     2
#define icup_charging_ActiveDays_wednesday_tag   3
#define icup_charging_ActiveDays_thursday_tag    4
#define icup_charging_ActiveDays_friday_tag      5
#define icup_charging_ActiveDays_saturday_tag    6
#define icup_charging_ActiveDays_sunday_tag      7
#define icup_charging_ChargeControlStatusUpdate_charge_control_status_tag 1
#define icup_charging_ChargeControlStatusUpdate_amp_limit_tag 2
#define icup_charging_ChargingLocationDeletedUpdate_uuid_tag 1
#define icup_charging_CreateChargingLocationResponse_uuid_tag 1
#define icup_charging_DeleteChargingLocationRequest_uuid_tag 1
#define icup_charging_GetChargeNowResponse_charge_now_tag 1
#define icup_charging_GetTargetSocResponse_target_soc_tag 1
#define icup_charging_GetTargetSocResponse_setting_tag 2
#define icup_charging_Position_latitude_tag      1
#define icup_charging_Position_longitude_tag     2
#define icup_charging_SetChargeNowRequest_charge_now_tag 1
#define icup_charging_SetTargetSocRequest_target_soc_tag 1
#define icup_charging_SetTargetSocRequest_setting_tag 2
#define icup_charging_TargetSocUpdate_target_soc_tag 1
#define icup_charging_TargetSocUpdate_setting_tag 2
#define icup_charging_DepartureTime_active_tag   1
#define icup_charging_DepartureTime_time_tag     2
#define icup_charging_DepartureTime_active_days_tag 3
#define icup_charging_ManualSchedule_active_tag  1
#define icup_charging_ManualSchedule_start_time_tag 2
#define icup_charging_ManualSchedule_end_time_tag 3
#define icup_charging_ManualSchedule_active_days_tag 4
#define icup_charging_Schedule_manual_schedule_tag 1
#define icup_charging_Schedule_departure_time_tag 2
#define icup_charging_Schedule_active_schedule_tag 3
#define icup_charging_ChargingLocationActualUpdate_uuid_tag 1
#define icup_charging_ChargingLocationActualUpdate_alias_tag 2
#define icup_charging_ChargingLocationActualUpdate_position_tag 3
#define icup_charging_ChargingLocationActualUpdate_amp_limit_tag 4
#define icup_charging_ChargingLocationActualUpdate_minimum_soc_tag 5
#define icup_charging_ChargingLocationActualUpdate_schedule_tag 6
#define icup_charging_ChargingLocationActualUpdate_smart_charging_supported_tag 7
#define icup_charging_ChargingLocationDefaultUpdate_uuid_tag 1
#define icup_charging_ChargingLocationDefaultUpdate_alias_tag 2
#define icup_charging_ChargingLocationDefaultUpdate_position_tag 3
#define icup_charging_ChargingLocationDefaultUpdate_amp_limit_tag 4
#define icup_charging_ChargingLocationDefaultUpdate_minimum_soc_tag 5
#define icup_charging_ChargingLocationDefaultUpdate_schedule_tag 6
#define icup_charging_ChargingLocationUpdate_uuid_tag 1
#define icup_charging_ChargingLocationUpdate_alias_tag 2
#define icup_charging_ChargingLocationUpdate_position_tag 3
#define icup_charging_ChargingLocationUpdate_amp_limit_tag 4
#define icup_charging_ChargingLocationUpdate_minimum_soc_tag 5
#define icup_charging_ChargingLocationUpdate_schedule_tag 6
#define icup_charging_ChargingLocationUpdate_smart_charging_supported_tag 7
#define icup_charging_CreateChargingLocationRequest_alias_tag 1
#define icup_charging_CreateChargingLocationRequest_position_tag 2
#define icup_charging_CreateChargingLocationRequest_amp_limit_tag 3
#define icup_charging_CreateChargingLocationRequest_minimum_soc_tag 4
#define icup_charging_CreateChargingLocationRequest_schedule_tag 5
#define icup_charging_CreateChargingLocationRequest_smart_charging_supported_tag 6
#define icup_charging_ModifyChargingLocationRequest_uuid_tag 1
#define icup_charging_ModifyChargingLocationRequest_alias_tag 2
#define icup_charging_ModifyChargingLocationRequest_position_tag 3
#define icup_charging_ModifyChargingLocationRequest_amp_limit_tag 4
#define icup_charging_ModifyChargingLocationRequest_minimum_soc_tag 5
#define icup_charging_ModifyChargingLocationRequest_schedule_tag 6
#define icup_charging_ModifyChargingLocationRequest_smart_charging_supported_tag 7
#define icup_charging_CurrentChargingSettingsUpdate_charging_controller_status_tag 1
#define icup_charging_CurrentChargingSettingsUpdate_current_location_tag 2
#define icup_charging_CurrentChargingSettingsUpdate_target_soc_tag 3
#define icup_charging_CurrentChargingSettingsUpdate_upcoming_schedule_start_time_tag 4
#define icup_charging_CurrentChargingSettingsUpdate_upcoming_schedule_end_time_tag 5
#define icup_charging_GetAllChargingLocationsResponse_default_location_tag 1
#define icup_charging_GetAllChargingLocationsResponse_actual_location_tag 2
#define icup_charging_GetAllChargingLocationsResponse_locations_tag 3

/* Struct field encoding specification for nanopb */
#define icup_charging_ActiveDays_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     monday,            1) \
X(a, STATIC,   SINGULAR, BOOL,     tuesday,           2) \
X(a, STATIC,   SINGULAR, BOOL,     wednesday,         3) \
X(a, STATIC,   SINGULAR, BOOL,     thursday,          4) \
X(a, STATIC,   SINGULAR, BOOL,     friday,            5) \
X(a, STATIC,   SINGULAR, BOOL,     saturday,          6) \
X(a, STATIC,   SINGULAR, BOOL,     sunday,            7)
#define icup_charging_ActiveDays_CALLBACK NULL
#define icup_charging_ActiveDays_DEFAULT NULL

#define icup_charging_ManualSchedule_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     active,            1) \
X(a, STATIC,   SINGULAR, UINT32,   start_time,        2) \
X(a, STATIC,   SINGULAR, UINT32,   end_time,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_days,       4)
#define icup_charging_ManualSchedule_CALLBACK NULL
#define icup_charging_ManualSchedule_DEFAULT NULL
#define icup_charging_ManualSchedule_active_days_MSGTYPE icup_charging_ActiveDays

#define icup_charging_DepartureTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     active,            1) \
X(a, STATIC,   SINGULAR, UINT32,   time,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_days,       3)
#define icup_charging_DepartureTime_CALLBACK NULL
#define icup_charging_DepartureTime_DEFAULT NULL
#define icup_charging_DepartureTime_active_days_MSGTYPE icup_charging_ActiveDays

#define icup_charging_Schedule_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  manual_schedule,   1) \
X(a, STATIC,   REPEATED, MESSAGE,  departure_time,    2) \
X(a, STATIC,   SINGULAR, UENUM,    active_schedule,   3)
#define icup_charging_Schedule_CALLBACK NULL
#define icup_charging_Schedule_DEFAULT NULL
#define icup_charging_Schedule_manual_schedule_MSGTYPE icup_charging_ManualSchedule
#define icup_charging_Schedule_departure_time_MSGTYPE icup_charging_DepartureTime

#define icup_charging_Position_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          1) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         2)
#define icup_charging_Position_CALLBACK NULL
#define icup_charging_Position_DEFAULT NULL

#define icup_charging_SetTargetSocRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   target_soc,        1) \
X(a, STATIC,   SINGULAR, UENUM,    setting,           2)
#define icup_charging_SetTargetSocRequest_CALLBACK NULL
#define icup_charging_SetTargetSocRequest_DEFAULT NULL

#define icup_charging_GetTargetSocResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   target_soc,        1) \
X(a, STATIC,   SINGULAR, UENUM,    setting,           2)
#define icup_charging_GetTargetSocResponse_CALLBACK NULL
#define icup_charging_GetTargetSocResponse_DEFAULT NULL

#define icup_charging_TargetSocUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   target_soc,        1) \
X(a, STATIC,   SINGULAR, UENUM,    setting,           2)
#define icup_charging_TargetSocUpdate_CALLBACK NULL
#define icup_charging_TargetSocUpdate_DEFAULT NULL

#define icup_charging_ChargingLocationUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   uuid,              1) \
X(a, STATIC,   SINGULAR, STRING,   alias,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          3) \
X(a, STATIC,   SINGULAR, UINT32,   amp_limit,         4) \
X(a, STATIC,   SINGULAR, UINT32,   minimum_soc,       5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  schedule,          6) \
X(a, STATIC,   SINGULAR, BOOL,     smart_charging_supported,   7)
#define icup_charging_ChargingLocationUpdate_CALLBACK NULL
#define icup_charging_ChargingLocationUpdate_DEFAULT NULL
#define icup_charging_ChargingLocationUpdate_position_MSGTYPE icup_charging_Position
#define icup_charging_ChargingLocationUpdate_schedule_MSGTYPE icup_charging_Schedule

#define icup_charging_CurrentChargingSettingsUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   charging_controller_status,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  current_location,   2) \
X(a, STATIC,   SINGULAR, UINT32,   target_soc,        3) \
X(a, STATIC,   SINGULAR, UINT32,   upcoming_schedule_start_time,   4) \
X(a, STATIC,   SINGULAR, UINT32,   upcoming_schedule_end_time,   5)
#define icup_charging_CurrentChargingSettingsUpdate_CALLBACK NULL
#define icup_charging_CurrentChargingSettingsUpdate_DEFAULT NULL
#define icup_charging_CurrentChargingSettingsUpdate_current_location_MSGTYPE icup_charging_ChargingLocationUpdate

#define icup_charging_ChargingLocationDefaultUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   uuid,              1) \
X(a, STATIC,   SINGULAR, STRING,   alias,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          3) \
X(a, STATIC,   SINGULAR, UINT32,   amp_limit,         4) \
X(a, STATIC,   SINGULAR, UINT32,   minimum_soc,       5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  schedule,          6)
#define icup_charging_ChargingLocationDefaultUpdate_CALLBACK NULL
#define icup_charging_ChargingLocationDefaultUpdate_DEFAULT NULL
#define icup_charging_ChargingLocationDefaultUpdate_position_MSGTYPE icup_charging_Position
#define icup_charging_ChargingLocationDefaultUpdate_schedule_MSGTYPE icup_charging_Schedule

#define icup_charging_ChargingLocationActualUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   uuid,              1) \
X(a, STATIC,   SINGULAR, STRING,   alias,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          3) \
X(a, STATIC,   SINGULAR, UINT32,   amp_limit,         4) \
X(a, STATIC,   SINGULAR, UINT32,   minimum_soc,       5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  schedule,          6) \
X(a, STATIC,   SINGULAR, BOOL,     smart_charging_supported,   7)
#define icup_charging_ChargingLocationActualUpdate_CALLBACK NULL
#define icup_charging_ChargingLocationActualUpdate_DEFAULT NULL
#define icup_charging_ChargingLocationActualUpdate_position_MSGTYPE icup_charging_Position
#define icup_charging_ChargingLocationActualUpdate_schedule_MSGTYPE icup_charging_Schedule

#define icup_charging_ChargeControlStatusUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    charge_control_status,   1) \
X(a, STATIC,   SINGULAR, UINT32,   amp_limit,         2)
#define icup_charging_ChargeControlStatusUpdate_CALLBACK NULL
#define icup_charging_ChargeControlStatusUpdate_DEFAULT NULL

#define icup_charging_CreateChargingLocationRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   alias,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2) \
X(a, STATIC,   SINGULAR, UINT32,   amp_limit,         3) \
X(a, STATIC,   SINGULAR, UINT32,   minimum_soc,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  schedule,          5) \
X(a, STATIC,   SINGULAR, BOOL,     smart_charging_supported,   6)
#define icup_charging_CreateChargingLocationRequest_CALLBACK NULL
#define icup_charging_CreateChargingLocationRequest_DEFAULT NULL
#define icup_charging_CreateChargingLocationRequest_position_MSGTYPE icup_charging_Position
#define icup_charging_CreateChargingLocationRequest_schedule_MSGTYPE icup_charging_Schedule

#define icup_charging_CreateChargingLocationResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   uuid,              1)
#define icup_charging_CreateChargingLocationResponse_CALLBACK NULL
#define icup_charging_CreateChargingLocationResponse_DEFAULT NULL

#define icup_charging_ModifyChargingLocationRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   uuid,              1) \
X(a, STATIC,   SINGULAR, STRING,   alias,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          3) \
X(a, STATIC,   SINGULAR, UINT32,   amp_limit,         4) \
X(a, STATIC,   SINGULAR, UINT32,   minimum_soc,       5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  schedule,          6) \
X(a, STATIC,   SINGULAR, BOOL,     smart_charging_supported,   7)
#define icup_charging_ModifyChargingLocationRequest_CALLBACK NULL
#define icup_charging_ModifyChargingLocationRequest_DEFAULT NULL
#define icup_charging_ModifyChargingLocationRequest_position_MSGTYPE icup_charging_Position
#define icup_charging_ModifyChargingLocationRequest_schedule_MSGTYPE icup_charging_Schedule

#define icup_charging_DeleteChargingLocationRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   uuid,              1)
#define icup_charging_DeleteChargingLocationRequest_CALLBACK NULL
#define icup_charging_DeleteChargingLocationRequest_DEFAULT NULL

#define icup_charging_ChargingLocationDeletedUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   uuid,              1)
#define icup_charging_ChargingLocationDeletedUpdate_CALLBACK NULL
#define icup_charging_ChargingLocationDeletedUpdate_DEFAULT NULL

#define icup_charging_GetAllChargingLocationsResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  default_location,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  actual_location,   2) \
X(a, STATIC,   REPEATED, MESSAGE,  locations,         3)
#define icup_charging_GetAllChargingLocationsResponse_CALLBACK NULL
#define icup_charging_GetAllChargingLocationsResponse_DEFAULT NULL
#define icup_charging_GetAllChargingLocationsResponse_default_location_MSGTYPE icup_charging_ChargingLocationDefaultUpdate
#define icup_charging_GetAllChargingLocationsResponse_actual_location_MSGTYPE icup_charging_ChargingLocationActualUpdate
#define icup_charging_GetAllChargingLocationsResponse_locations_MSGTYPE icup_charging_ChargingLocationUpdate

#define icup_charging_SetChargeNowRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     charge_now,        1)
#define icup_charging_SetChargeNowRequest_CALLBACK NULL
#define icup_charging_SetChargeNowRequest_DEFAULT NULL

#define icup_charging_GetChargeNowResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     charge_now,        1)
#define icup_charging_GetChargeNowResponse_CALLBACK NULL
#define icup_charging_GetChargeNowResponse_DEFAULT NULL

extern const pb_msgdesc_t icup_charging_ActiveDays_msg;
extern const pb_msgdesc_t icup_charging_ManualSchedule_msg;
extern const pb_msgdesc_t icup_charging_DepartureTime_msg;
extern const pb_msgdesc_t icup_charging_Schedule_msg;
extern const pb_msgdesc_t icup_charging_Position_msg;
extern const pb_msgdesc_t icup_charging_SetTargetSocRequest_msg;
extern const pb_msgdesc_t icup_charging_GetTargetSocResponse_msg;
extern const pb_msgdesc_t icup_charging_TargetSocUpdate_msg;
extern const pb_msgdesc_t icup_charging_ChargingLocationUpdate_msg;
extern const pb_msgdesc_t icup_charging_CurrentChargingSettingsUpdate_msg;
extern const pb_msgdesc_t icup_charging_ChargingLocationDefaultUpdate_msg;
extern const pb_msgdesc_t icup_charging_ChargingLocationActualUpdate_msg;
extern const pb_msgdesc_t icup_charging_ChargeControlStatusUpdate_msg;
extern const pb_msgdesc_t icup_charging_CreateChargingLocationRequest_msg;
extern const pb_msgdesc_t icup_charging_CreateChargingLocationResponse_msg;
extern const pb_msgdesc_t icup_charging_ModifyChargingLocationRequest_msg;
extern const pb_msgdesc_t icup_charging_DeleteChargingLocationRequest_msg;
extern const pb_msgdesc_t icup_charging_ChargingLocationDeletedUpdate_msg;
extern const pb_msgdesc_t icup_charging_GetAllChargingLocationsResponse_msg;
extern const pb_msgdesc_t icup_charging_SetChargeNowRequest_msg;
extern const pb_msgdesc_t icup_charging_GetChargeNowResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define icup_charging_ActiveDays_fields &icup_charging_ActiveDays_msg
#define icup_charging_ManualSchedule_fields &icup_charging_ManualSchedule_msg
#define icup_charging_DepartureTime_fields &icup_charging_DepartureTime_msg
#define icup_charging_Schedule_fields &icup_charging_Schedule_msg
#define icup_charging_Position_fields &icup_charging_Position_msg
#define icup_charging_SetTargetSocRequest_fields &icup_charging_SetTargetSocRequest_msg
#define icup_charging_GetTargetSocResponse_fields &icup_charging_GetTargetSocResponse_msg
#define icup_charging_TargetSocUpdate_fields &icup_charging_TargetSocUpdate_msg
#define icup_charging_ChargingLocationUpdate_fields &icup_charging_ChargingLocationUpdate_msg
#define icup_charging_CurrentChargingSettingsUpdate_fields &icup_charging_CurrentChargingSettingsUpdate_msg
#define icup_charging_ChargingLocationDefaultUpdate_fields &icup_charging_ChargingLocationDefaultUpdate_msg
#define icup_charging_ChargingLocationActualUpdate_fields &icup_charging_ChargingLocationActualUpdate_msg
#define icup_charging_ChargeControlStatusUpdate_fields &icup_charging_ChargeControlStatusUpdate_msg
#define icup_charging_CreateChargingLocationRequest_fields &icup_charging_CreateChargingLocationRequest_msg
#define icup_charging_CreateChargingLocationResponse_fields &icup_charging_CreateChargingLocationResponse_msg
#define icup_charging_ModifyChargingLocationRequest_fields &icup_charging_ModifyChargingLocationRequest_msg
#define icup_charging_DeleteChargingLocationRequest_fields &icup_charging_DeleteChargingLocationRequest_msg
#define icup_charging_ChargingLocationDeletedUpdate_fields &icup_charging_ChargingLocationDeletedUpdate_msg
#define icup_charging_GetAllChargingLocationsResponse_fields &icup_charging_GetAllChargingLocationsResponse_msg
#define icup_charging_SetChargeNowRequest_fields &icup_charging_SetChargeNowRequest_msg
#define icup_charging_GetChargeNowResponse_fields &icup_charging_GetChargeNowResponse_msg

/* Maximum encoded size of messages (where known) */
#define icup_charging_ActiveDays_size            14
#define icup_charging_ChargeControlStatusUpdate_size 8
#define icup_charging_ChargingLocationActualUpdate_size 614
#define icup_charging_ChargingLocationDefaultUpdate_size 612
#define icup_charging_ChargingLocationDeletedUpdate_size 38
#define icup_charging_ChargingLocationUpdate_size 614
#define icup_charging_CreateChargingLocationRequest_size 576
#define icup_charging_CreateChargingLocationResponse_size 38
#define icup_charging_CurrentChargingSettingsUpdate_size 641
#define icup_charging_DeleteChargingLocationRequest_size 38
#define icup_charging_DepartureTime_size         24
#define icup_charging_GetAllChargingLocationsResponse_size 13572
#define icup_charging_GetChargeNowResponse_size  2
#define icup_charging_GetTargetSocResponse_size  8
#define icup_charging_ManualSchedule_size        30
#define icup_charging_ModifyChargingLocationRequest_size 614
#define icup_charging_Position_size              18
#define icup_charging_Schedule_size              408
#define icup_charging_SetChargeNowRequest_size   2
#define icup_charging_SetTargetSocRequest_size   8
#define icup_charging_TargetSocUpdate_size       8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
