/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_BATTERYCHARGE_SETOPTIMIZEDCHARGINGSCHEDULE_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_BATTERYCHARGE_SETOPTIMIZEDCHARGINGSCHEDULE_PB_H_INCLUDED
#include <pb.h>
#include "entities/common/ResponseStatus.pb.h"
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _remote_control_OptimizedChargingScheduleInvalidationReason { 
    remote_control_OptimizedChargingScheduleInvalidationReason_OPTIMIZED_CHARGING_SCHEDULE_INVALIDATION_REASON_UNSPECIFIED = 0, 
    remote_control_OptimizedChargingScheduleInvalidationReason_OPTIMIZED_CHARGING_SCHEDULE_INVALIDATION_REASON_EXPIRED = 1, 
    remote_control_OptimizedChargingScheduleInvalidationReason_OPTIMIZED_CHARGING_SCHEDULE_INVALIDATION_REASON_CHARGER_DISCONNECTED = 2, 
    remote_control_OptimizedChargingScheduleInvalidationReason_OPTIMIZED_CHARGING_SCHEDULE_INVALIDATION_REASON_DRIVING = 3, 
    remote_control_OptimizedChargingScheduleInvalidationReason_OPTIMIZED_CHARGING_SCHEDULE_INVALIDATION_REASON_MANUAL_SCHEDULE_ACTIVATED = 4 
} remote_control_OptimizedChargingScheduleInvalidationReason;

/* Struct definitions */
/* OID {1.3.6.1.4.1.37916.3.6.21.7.2.2} */
typedef struct _remote_control_SetOptimizedChargingScheduleRequest { 
    pb_callback_t uuid; /* uuid to identify the ChargingLocation that owns these timers */
    pb_callback_t timers; /* Agreed max is 100 */
} remote_control_SetOptimizedChargingScheduleRequest;

/* This update is emitted when the optimized schedule in TCAM is invalidated for some reason.
OID {1.3.6.1.4.1.37916.3.6.21.7.4.1} */
typedef struct _remote_control_OptimizedChargingScheduleInvalidatedUpdate { 
    remote_control_OptimizedChargingScheduleInvalidationReason reason; 
} remote_control_OptimizedChargingScheduleInvalidatedUpdate;

typedef struct _remote_control_OptimizedChargingTimer { 
    bool has_start_time;
    google_protobuf_Timestamp start_time; /* UTC+0 Time - The nanos part of the Timestamp may be ignored */
    bool has_stop_time;
    google_protobuf_Timestamp stop_time; /* UTC+0 Time - The nanos part of the Timestamp may be ignored */
    uint32_t amp_limit; 
} remote_control_OptimizedChargingTimer;

/* OID {1.3.6.1.4.1.37916.3.6.21.7.2.3} */
typedef struct _remote_control_SetOptimizedChargingScheduleResponse { 
    bool has_response_status;
    common_ResponseStatus response_status; /* required */
} remote_control_SetOptimizedChargingScheduleResponse;


/* Helper constants for enums */
#define _remote_control_OptimizedChargingScheduleInvalidationReason_MIN remote_control_OptimizedChargingScheduleInvalidationReason_OPTIMIZED_CHARGING_SCHEDULE_INVALIDATION_REASON_UNSPECIFIED
#define _remote_control_OptimizedChargingScheduleInvalidationReason_MAX remote_control_OptimizedChargingScheduleInvalidationReason_OPTIMIZED_CHARGING_SCHEDULE_INVALIDATION_REASON_MANUAL_SCHEDULE_ACTIVATED
#define _remote_control_OptimizedChargingScheduleInvalidationReason_ARRAYSIZE ((remote_control_OptimizedChargingScheduleInvalidationReason)(remote_control_OptimizedChargingScheduleInvalidationReason_OPTIMIZED_CHARGING_SCHEDULE_INVALIDATION_REASON_MANUAL_SCHEDULE_ACTIVATED+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_OptimizedChargingTimer_init_default {false, google_protobuf_Timestamp_init_default, false, google_protobuf_Timestamp_init_default, 0}
#define remote_control_SetOptimizedChargingScheduleRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define remote_control_SetOptimizedChargingScheduleResponse_init_default {false, common_ResponseStatus_init_default}
#define remote_control_OptimizedChargingScheduleInvalidatedUpdate_init_default {_remote_control_OptimizedChargingScheduleInvalidationReason_MIN}
#define remote_control_OptimizedChargingTimer_init_zero {false, google_protobuf_Timestamp_init_zero, false, google_protobuf_Timestamp_init_zero, 0}
#define remote_control_SetOptimizedChargingScheduleRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define remote_control_SetOptimizedChargingScheduleResponse_init_zero {false, common_ResponseStatus_init_zero}
#define remote_control_OptimizedChargingScheduleInvalidatedUpdate_init_zero {_remote_control_OptimizedChargingScheduleInvalidationReason_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_SetOptimizedChargingScheduleRequest_uuid_tag 1
#define remote_control_SetOptimizedChargingScheduleRequest_timers_tag 2
#define remote_control_OptimizedChargingScheduleInvalidatedUpdate_reason_tag 1
#define remote_control_OptimizedChargingTimer_start_time_tag 1
#define remote_control_OptimizedChargingTimer_stop_time_tag 2
#define remote_control_OptimizedChargingTimer_amp_limit_tag 3
#define remote_control_SetOptimizedChargingScheduleResponse_response_status_tag 1

/* Struct field encoding specification for nanopb */
#define remote_control_OptimizedChargingTimer_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  start_time,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stop_time,         2) \
X(a, STATIC,   SINGULAR, UINT32,   amp_limit,         3)
#define remote_control_OptimizedChargingTimer_CALLBACK NULL
#define remote_control_OptimizedChargingTimer_DEFAULT NULL
#define remote_control_OptimizedChargingTimer_start_time_MSGTYPE google_protobuf_Timestamp
#define remote_control_OptimizedChargingTimer_stop_time_MSGTYPE google_protobuf_Timestamp

#define remote_control_SetOptimizedChargingScheduleRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   uuid,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  timers,            2)
#define remote_control_SetOptimizedChargingScheduleRequest_CALLBACK pb_default_field_callback
#define remote_control_SetOptimizedChargingScheduleRequest_DEFAULT NULL
#define remote_control_SetOptimizedChargingScheduleRequest_timers_MSGTYPE remote_control_OptimizedChargingTimer

#define remote_control_SetOptimizedChargingScheduleResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  response_status,   1)
#define remote_control_SetOptimizedChargingScheduleResponse_CALLBACK NULL
#define remote_control_SetOptimizedChargingScheduleResponse_DEFAULT NULL
#define remote_control_SetOptimizedChargingScheduleResponse_response_status_MSGTYPE common_ResponseStatus

#define remote_control_OptimizedChargingScheduleInvalidatedUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            1)
#define remote_control_OptimizedChargingScheduleInvalidatedUpdate_CALLBACK NULL
#define remote_control_OptimizedChargingScheduleInvalidatedUpdate_DEFAULT NULL

extern const pb_msgdesc_t remote_control_OptimizedChargingTimer_msg;
extern const pb_msgdesc_t remote_control_SetOptimizedChargingScheduleRequest_msg;
extern const pb_msgdesc_t remote_control_SetOptimizedChargingScheduleResponse_msg;
extern const pb_msgdesc_t remote_control_OptimizedChargingScheduleInvalidatedUpdate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_OptimizedChargingTimer_fields &remote_control_OptimizedChargingTimer_msg
#define remote_control_SetOptimizedChargingScheduleRequest_fields &remote_control_SetOptimizedChargingScheduleRequest_msg
#define remote_control_SetOptimizedChargingScheduleResponse_fields &remote_control_SetOptimizedChargingScheduleResponse_msg
#define remote_control_OptimizedChargingScheduleInvalidatedUpdate_fields &remote_control_OptimizedChargingScheduleInvalidatedUpdate_msg

/* Maximum encoded size of messages (where known) */
/* remote_control_SetOptimizedChargingScheduleRequest_size depends on runtime parameters */
#define remote_control_OptimizedChargingScheduleInvalidatedUpdate_size 2
#define remote_control_OptimizedChargingTimer_size 54
#if defined(common_ResponseStatus_size)
#define remote_control_SetOptimizedChargingScheduleResponse_size (6 + common_ResponseStatus_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
