namespace DA_Common.Barony
{
    /// <summary>A known lord of the Eastern March (shared reference roster).</summary>
    public sealed record KnownLordEntry(
        string Name,
        string House,
        string Title,
        string Holdings,
        string Description,
        string ProducedGoods,
        string DemandedGoods);

    /// <summary>
    /// Global catalog of known lords of Wschodnia Marchia.
    /// Shared identically for every barony (reference / trade lore).
    /// </summary>
    public static class KnownLordsCatalog
    {
        public const string RegionEasternMarch = "Wschodnia Marchia";

        public static IReadOnlyList<KnownLordEntry> EasternMarch { get; } = new KnownLordEntry[]
        {
            new(
                Name: @"Alysson",
                House: @"Whitclaw",
                Title: @"Baronet",
                Holdings: @"Riolle (wioska)",
                Description: @"Piękny, niski, szczupły blondyn. Znany z bycia mężem córki Margrabiego. W posagu otrzymał wioskę niedalego Warrington",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Ammett",
                House: @"Staedronth",
                Title: @"Baron",
                Holdings: @"Westhills",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Aren",
                House: @"Rollford",
                Title: @"Hrabia",
                Holdings: @"King’s Peace",
                Description: @"Pochodzi ze starego, kildradzkiego rodu który jako jedyny nawiązał handel z elfami z Lorathrien. Dzięki temu Imperium pozwoliło mu zatrzymać ziemie, po złożeniu hołdu. Dostojny, szczupły, znany z umiłowania biżuterii i ubioru elfów z Lorathrien",
                ProducedGoods: @"Wyroby leśnych elfów, luksusowe drewno, zioła i korzenie",
                DemandedGoods: @"zboże, żelazo, miedź, sól, kamienie o metale szlachetne"),
            new(
                Name: @"Argewald",
                House: @"Canterill",
                Title: @"Markiz",
                Holdings: @"Totham",
                Description: @"Sprytny, obrotny i miłujący złoto markiz, wchodzący w skład triumwiratu rządzącego Wschodnią Marchią. Wyznawca Tarata.",
                ProducedGoods: @"Zboże, wełna, tkaniny, mięso, skóry",
                DemandedGoods: @"Broń, wszelkie towary luksusowe, drewno,  kamień, żelazo, miedź, futra, papier"),
            new(
                Name: @"Arienna",
                House: @"Coler",
                Title: @"Baronesa",
                Holdings: @"Thyruswill",
                Description: @"Sprytna, zręczna polityk o słabym rodowodzie, który rekompensuje wdziękiem i naturalnym magnetyzmem. Mimo konfliktu z seniorem udało jej się zatrzymać i rozwinąć baronię dzięki wdanie się  w łaski Margrabiego Hardwina. Wieczna wdowa",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Balon",
                House: @"Greywarden",
                Title: @"Wicehrabia",
                Holdings: @"Easthills",
                Description: @"Dumny kuzyn margrabiego Greywarda  Balon dał się poznać jako surowy i silny lord, jego wyroki są sprawiedliwe, a tereny przez niego kontrolowane bezpieczne.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Bedjer",
                House: @"Dyernedi",
                Title: @"Arcybiskup Kościoła Thyrusa",
                Holdings: @"Ziemie w i wokół Warrington",
                Description: @"Wśród elity słynie z żyłki do interesów i umiłowania do złota.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Benam",
                House: @"Greenfield",
                Title: @"Baron",
                Holdings: @"Boldbeak",
                Description: @"Bardzo stary, uległy, pokojowy.  Ma dwóch synów: Benneta i Benwina.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Borwin",
                House: @"Nuller",
                Title: @"Baronet",
                Holdings: @"Whiteoak (wioska)",
                Description: @"Ogromny baronetem z King’s Peace, który potrafi wypić ogromne ilości alkoholu i pochłonąć małego dzika w ciągu jednej uczty.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Braddock",
                House: @"Wynch",
                Title: @"Baron",
                Holdings: @"Direward",
                Description: @"Przygarbiony, łysawy człowiek o grubych binoklach, koło pięćdziesiątki. Znany ze swojej lojalności do żony i mizenrej postury",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Brant",
                House: @"Slynor",
                Title: @"Baron",
                Holdings: @"Oakencoast",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Clarrik",
                House: @"Sadelyn",
                Title: @"Hrabia",
                Holdings: @"Hawk Greeting",
                Description: @"Postawny mężczyzna o surowym wzroku i dumnym kroku. Ma bogatą stadninę i duży wpływ na politykę jako że jego kuzynem jest Arcybiskup Bedjer Dyernedi - najwyższy kapłan Thyrusa w Marchii.",
                ProducedGoods: @"konie, konie bojowe, konie arystokratyczne",
                DemandedGoods: @"Zboża(owies), towary luksusowe, drewno, żelazo"),
            new(
                Name: @"Colren",
                House: @"Warrin",
                Title: @"Baron",
                Holdings: @"Ilow",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Corlin",
                House: @"Werdhog",
                Title: @"Baron",
                Holdings: @"Klin",
                Description: @"Otyły baron z Klin. Od kilku lat walczył z lodem Olgredem z Brie. Zatrudnił wtedy bardzo wątpliwej moralności najemników, którzy jednak zdołali znacząco dopomóc w obronie domeny.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Dalran",
                House: @"Spyre",
                Title: @"Baron",
                Holdings: @"Irtow",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Darrin",
                House: @"Edgerton",
                Title: @"Baron",
                Holdings: @"Keatlow",
                Description: @"Bardzo ambitny i wojowniczy. Jego starsi bracia zginęli w dziwnych okolicznościach. Po przejęciu władzy zagrabił ziemie sąsiadów.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Dramon",
                House: @"Hastwyck",
                Title: @"Baron",
                Holdings: @"Forestedge",
                Description: @"Mody, ambitny syn lorda Kevena Hastwycka z Dawntree. Wybudował pokaźną twierdzę, choć nikt nie potrafi wytłumaczyć skąd miał na to fundusze",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Dunna",
                House: @"Koltberg",
                Title: @"Baronet",
                Holdings: @"Holdywag (wioska)",
                Description: @"Jeden z Koldbergów - znanego z biedoty i dzikości rodu z kotliny Koltbergów. Koltbergowie nie są zbyt szanowani, a często i nieuznawani na arenie politycznej Wschodniej Marchii",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Durisug",
                House: @"Dag’Thorak",
                Title: @"Markiz (Górski Książe)",
                Holdings: @"Groundfall",
                Description: @"Twardy, niezłomny i dumny krasnoludzki władca górskiej twierdzy. Bezpośredni wasal Margrabiego. Nie ma oficjalnej władzy nad Marchią, ale jego znanie jest szanowane.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Dyron",
                House: @"Greatwing",
                Title: @"Baron",
                Holdings: @"Hurtbow",
                Description: @"Wysoki, chudy, mało ambitny. Znany z inteligencji, zamiłowania do nauki, logiki i gier. Wyznaczony przez Margrabiego na władce Hurtbow - problematycznej baronii przy puszczy Irredale",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Eldren",
                House: @"Morat",
                Title: @"Baron",
                Holdings: @"Moratz",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Erac",
                House: @"Mertyn",
                Title: @"Hrabia",
                Holdings: @"Willow Hill",
                Description: @"Lojalny wasal Margrabiego. Mistrz łowczy i protektor puszczy. Po pięćdziesiątce ale w dobrej formie",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Erwald",
                House: @"Clifford",
                Title: @"Baron",
                Holdings: @"Earthcliff",
                Description: @"Brat bliźniak Parwelda, który rządzi Newcliff. Bracia walczą ze sobą od kilku lat.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Garrel",
                House: @"Tudbury",
                Title: @"Baron",
                Holdings: @"Waterhall",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Goller",
                House: @"von Egglitz",
                Title: @"Hrabia",
                Holdings: @"Nieruchomości w Warrington",
                Description: @"Hrabią był jedynie z tytułu. Bogaty, członek rady Warrington, ma niewielką flotę handlową podróżującą na terenach od Imperium aż po Solime, oraz jeszcze kilka pomniejszych biznesów",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Graige",
                House: @"Oatwright",
                Title: @"Baron",
                Holdings: @"Darklyn",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Gron",
                House: @"Duevaft",
                Title: @"Baron",
                Holdings: @"Lonehill",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Hardwin",
                House: @"Greatwing",
                Title: @"Margrabia",
                Holdings: @"Warrington",
                Description: @"Postwny, dumny, władczy, pełen splendoru mężczyzna około pięśdziesiątki. Jest nadzorcom Triumwiratu i nieoficjalnym władcą Wschodniej Marchii. Wyznawca Thyrusa",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Herrath",
                House: @"Highhill",
                Title: @"Baron",
                Holdings: @"Summerhall",
                Description: @"Wielki mężczyzna o łagodnym usposobieniu i miłości do egzotycznych potraw.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Huel",
                House: @"Blackfyre",
                Title: @"Baron",
                Holdings: @"Gillamoor",
                Description: @"Pasowany na rycerza już w wieku 14 lat, po Bitwie o Przełęcz. Dzięki wojowniczemu usposobieniu, wytrwałości i braku skrupułów zdobył pozycję barona o jednej z większych domen i armii we Wschodniej Marchii",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Igwar",
                House: @"Zorren",
                Title: @"Baron",
                Holdings: @"Olm",
                Description: @"Młody, brzydki chłopak, mało znany i mało interesujący",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Jardan",
                House: @"Ferren",
                Title: @"Baron",
                Holdings: @"Ogrville",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Jerald",
                House: @"Grann",
                Title: @"Wicehrabia",
                Holdings: @"Brodlow",
                Description: @"Walczy z hordą goblinów nękających jego ziemie od ponad dwudziestu lat. Stracił  na wojnach z goblinami dwóch synów ponoć nienawidzi ich tak bardzo, że niegdyś pozbawiony broni i osaczony, zagryzł wszystkich i wydłubał im oczy palcami.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Jorah",
                House: @"Parren",
                Title: @"Baron",
                Holdings: @"Last Inn",
                Description: @"Postawnej budowy w średnim wieku o szerokich barkach, gęstych bokobrodach i surowym spojrzeniu znad szerokiego, źle zrośniętego nosa. Dumny mężczyzna o nieposzkalowanej opini. Jego syn i dziedzic  Ivern ma sparaliżowane nogi i nie potrafi chodzić.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Kyllan",
                House: @"Stingryn",
                Title: @"Baron",
                Holdings: @"Cywell",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Lancion",
                House: @"Practor",
                Title: @"Hrabia",
                Holdings: @"Gray Obelisk",
                Description: @"hrabia dużego handlowego węzła na głównej rzece Warrington. Hrabia Lancion był wyniosłym, korpulentnym mężczyznom o dużym apetycie i umiłowaniu do hazardu",
                ProducedGoods: @"Zboża, Sery, ceramika",
                DemandedGoods: @"tkaniny, sól, drewno"),
            new(
                Name: @"Liram",
                House: @"Kettleblack",
                Title: @"Baron",
                Holdings: @"Lorenmill",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Lother",
                House: @"Whistleblow",
                Title: @"Baron",
                Holdings: @"Pitchfork",
                Description: @"Stary, doświadczony wyga życia politycznego. Dobry znajomy Markiza Argewalda Canterilla. Ukontentowany z życia, lojalny wasal i miłośnik uczt wszelakich",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Melevan",
                House: @"Mirrforge",
                Title: @"Wicehrabia",
                Holdings: @"Dreton",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Mevir",
                House: @"Darkfrost",
                Title: @"Baron",
                Holdings: @"Bonefyre",
                Description: @"Były kapitan Inkwizycji, awansowany do statusu barona za zasługi i zdolności",
                ProducedGoods: @"Drewno, skóry, futra",
                DemandedGoods: @"Wyroby metalowe, zboża, sól"),
            new(
                Name: @"Myrton",
                House: @"Greyward",
                Title: @"Markiz",
                Holdings: @"Betforge",
                Description: @"Honorowy, lojalny i sprawiedliwy weteran wojny o Kildrad. Markiz wchodzący w skład triumwiratu. Wyznawca Ura.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Nathar",
                House: @"Warrin",
                Title: @"Baron",
                Holdings: @"Warning Arrow",
                Description: @"Przystojny i zadbany, nienagannym ubiorze z licznymi elementami stroju leśnych elfów. Raczej oszczędny w emocjach, ale uprzejmy",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Nowald",
                House: @"Greatwing",
                Title: @"Baronet",
                Holdings: @"Nerton (wieś przy Warrington)",
                Description: @"syn kuzyna margrabiego Hardwina Greatwinga. Postawny, wysoki brunet około trzydziestki. Wpływowy i ambitny",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Olgred",
                House: @"Trur",
                Title: @"Wicehrabia",
                Holdings: @"Brie",
                Description: @"Z kildradzkiego rodu. Po śmierci ojca zmienił baronię w strefę militarną. Wdał się w wojnę z lordem Werdhogiem z Klin, której nie potrafił wygrać",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Orswal",
                House: @"Goodwill",
                Title: @"Baron",
                Holdings: @"Bearbury",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Parweld",
                House: @"Clifford",
                Title: @"Baron",
                Holdings: @"Newcliff",
                Description: @"Brat bliźniak Erwalda, który rządzi Earthcliff. Bracia walczą ze sobą od kilku lat.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Payton",
                House: @"Highcrow",
                Title: @"Wicehrabia",
                Holdings: @"Northlap",
                Description: @"Władca rodu i podgórskiej osady otoczonej dzikimi lasami na zachodzie. Kontrolują zachodnią granicę i pilnuje Gór Krańcowych. Krążą plotki o ich powiązaniach z wiedźmami",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Piff",
                House: @"Hogger",
                Title: @"Baron",
                Holdings: @"Hogbridge",
                Description: @"Czwarty syn lorda Ogwala. (Trzech poprzednich zginęło w dziwnych okolicznościach) Masywny, otyły, silny, śmierdzący. Wygląda na głupszego niż jest w rzeczywistości.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Pranar",
                House: @"Cheswright",
                Title: @"Baron",
                Holdings: @"Lafast",
                Description: @"Podstażały baron ze szlachetnego rodu. Słowny, honorowy i dumny. Znany jest z rozsądku i rozwagi, oraz dobrego doboru ludzi.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Ruger",
                House: @"Lydden",
                Title: @"Baron",
                Holdings: @"Fillbury",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Ryher",
                House: @"Tarwin",
                Title: @"Baron",
                Holdings: @"Bredow",
                Description: @"Wywołał konflikt z Vorgoweldami, który zamienił dostatnią domenę o handlowym charakterzew targany wojnami, zniszczony zmilitaryzowany teren.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Sulvan",
                House: @"Tarpp",
                Title: @"Baron",
                Holdings: @"Timberhill",
                Description: @"Ogromny mężczyzn o wielkiej sile i zdolnościach bojowych. O dziwo znany jest z łagodnej natury i miłości do zwierząt.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Thaddeus",
                House: @"Direbolt",
                Title: @"Baron",
                Holdings: @"Darkhold",
                Description: @"Odznaczony generał, weteran wojny z jaszczuroludzmi, przybyły z głębi Imperium. Pochodzi ze znaczącej, bogatej i honorowej rodziny",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Tirus",
                House: @"Donniger",
                Title: @"Wicehrabia",
                Holdings: @"Madtree",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Turen",
                House: @"Koltberg",
                Title: @"Baronet",
                Holdings: @"Um (wioska)",
                Description: @"Jeden z Koldbergów - znanego z biedoty i dzikości rodu z kotliny Koltbergów. Koltbergowie nie są zbyt szanowani, a często i nieuznawani na arenie politycznej Wschodniej Marchii",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Urven",
                House: @"Blackward",
                Title: @"Baron",
                Holdings: @"Orlyn",
                Description: @"Legitymizowany bękart z gałęzi Graywardów, dalszy krewny Myrtona.  Zręczny i litościwy władca, dba o poddanych i ich dobrobyt. Organizator “Królewskich polowań”, bardzo popularnych wśród elity",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Virrol",
                House: @"Lonetower",
                Title: @"Wicehrabia",
                Holdings: @"Zinth",
                Description: @"Serdeczny, miły oraz inteligentny, choć bardzo wątłej postury i raczej tchórzliwy. Mimo tego jest dobrym zarządcą całkiem bogatego Zinth.",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Volenbert",
                House: @"Oxenverd",
                Title: @"Baronet",
                Holdings: @"ziemie przy Warrington",
                Description: @"Starszy, niedawno stracił córkę Viviennę",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Vortigern",
                House: @"Blackhammer",
                Title: @"Baron",
                Holdings: @"Blackhammer",
                Description: @"Niedawno wyniesiony na lorda władca Doliny Blackhammer. Były najemnik o tajemniczej przeszłości i renomie zdolnego i zaradnego wojownika",
                ProducedGoods: @"kamień, żelazo, miedź",
                DemandedGoods: @"zboża, skóry, tkaniny"),
            new(
                Name: @"Welron",
                House: @"Sprentrack",
                Title: @"Enforest",
                Holdings: @"Redpine",
                Description: @"",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Will Jąkała",
                House: @"Koltberg",
                Title: @"Baronet",
                Holdings: @"Arg (wioska)",
                Description: @"Jeden z Koldbergów - znanego z biedoty i dzikości rodu z kotliny Koltbergów. Koltbergowie nie są zbyt szanowani, a często i nieuznawani na arenie politycznej Wschodniej Marchii",
                ProducedGoods: @"",
                DemandedGoods: @""),
            new(
                Name: @"Yagga",
                House: @"Wildberry",
                Title: @"Baronesa",
                Holdings: @"Borolin",
                Description: @"Stary ród jeszcze z czasów Kilgradu. Na jego czele stoi młoda, piękna i wojownicza Yagga, której urodzie dorównuje jedynie siła jej gniewu.",
                ProducedGoods: @"",
                DemandedGoods: @""),
        };
    }
}
