namespace DA_Common.Barony
{
    /// <summary>A known lord of the Eastern March (shared reference roster).</summary>
    public sealed record KnownLordEntry(
        string Name,
        string House,
        string Title,
        string Holdings,
        string Description,
        string ProducedGoods,
        string DemandedGoods,
        int Wealth); // 1=destitute … 4=average barony … 6=Totham … 7=Warrington … 10=Imperial capital

    /// <summary>
    /// Global catalog of known lords of the Eastern March.
    /// Shared identically for every barony (reference / trade lore).
    /// </summary>
    public static partial class KnownLordsCatalog
    {
        public const string RegionEasternMarch = "Eastern March";

        public static IReadOnlyList<KnownLordEntry> EasternMarch { get; } = new KnownLordEntry[]
        {
            new(
                Name: "Alysson",
                House: "Whitclaw",
                Title: "Baronet",
                Holdings: "Riolle (village)",
                Description: "A handsome, short, slender blond. Known as the husband of the Margrave's daughter; he received a village near Warrington as her dowry.",
                ProducedGoods: "Wine, Cloth, Cheese",
                DemandedGoods: "Silk, Spices, Gold",
                Wealth: 2),
            new(
                Name: "Ammett",
                House: "Staedronth",
                Title: "Baron",
                Holdings: "Westhills",
                Description: "A quiet hill-country baron who keeps Westhills orderly and unremarkable. Prefers local justice and steady harvests over court intrigue in Warrington.",
                ProducedGoods: "Wool, Cheese, Building stone, Honey & wax",
                DemandedGoods: "Iron, Salt, Cloth, Soft metals",
                Wealth: 3),
            new(
                Name: "Aren",
                House: "Rollford",
                Title: "Count",
                Holdings: "King's Peace",
                Description: "From an old Kildrad house—the only one to open trade with the elves of Lorathrien. The Empire let him keep his lands after he swore fealty. Dignified and slim, known for loving Lorathrien jewelry and dress.",
                ProducedGoods: "Elven forest crafts, Elven alder, Herbs & roots, Honey & wax, Dyes, Glass",
                DemandedGoods: "Iron, Soft metals, Salt, Wine, Paper, Bricks",
                Wealth: 5),
            new(
                Name: "Argewald",
                House: "Canterill",
                Title: "Marquis",
                Holdings: "Totham",
                Description: "A clever, restless, gold-loving marquis and member of the triumvirate that rules the Eastern March. A devotee of Tarat.",
                ProducedGoods: "Wool, Cloth, Leather, Cheese, Flax & hemp, Horses, Bricks",
                DemandedGoods: "Military weapons, Silk, Paper, Spices, Gold, Glass, War horses",
                Wealth: 6),
            new(
                Name: "Arienna",
                House: "Coler",
                Title: "Baroness",
                Holdings: "Thyruswill",
                Description: "A sharp, adroit politician of weak blood who makes up for it with charm and natural magnetism. Despite a quarrel with her liege she kept and grew her barony by winning Margrave Hardwin's favour. A perpetual widow of Lord Luden Canterill.",
                ProducedGoods: "Salted fish & meat, Cloth, Dyes, Glass, Wine",
                DemandedGoods: "Gold, Spices, Iron, Soft metals, Silk",
                Wealth: 4),
            new(
                Name: "Balon",
                House: "Greywarden",
                Title: "Viscount",
                Holdings: "Easthills",
                Description: "Proud cousin of Margrave Greyward. Known as a stern, strong lord whose judgments are fair and whose lands stay safe.",
                ProducedGoods: "Iron, Soft metals, Silver, Building stone, Granite, Gold",
                DemandedGoods: "Salted fish & meat, Salt, Cloth, Wine, Paper, Military weapons",
                Wealth: 5),
            new(
                Name: "Bedjer",
                House: "Dyernedi",
                Title: "Archbishop of the Church of Thyrus",
                Holdings: "Lands in and around Warrington",
                Description: "Among the elite he is famed for a merchant's instinct and a love of gold.",
                ProducedGoods: "Paper, Glass, Gold, Wine, Cloth, Ceramics",
                DemandedGoods: "Silk, Spices, Ivory & walrus bone, Soft metals, Horses, Gemstones",
                Wealth: 5),
            new(
                Name: "Benam",
                House: "Greenfield",
                Title: "Baron",
                Holdings: "Boldbeak",
                Description: "Very old, yielding, and peaceable. Has two sons: Bennet and Benwin.",
                ProducedGoods: "Wool, Cheese, Honey & wax, Flax & hemp",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Borwin",
                House: "Nuller",
                Title: "Baronet",
                Holdings: "Whiteoak (village)",
                Description: "A huge baronet from King's Peace who can drink vast amounts of alcohol and finish a small boar in a single feast.",
                ProducedGoods: "Honey & wax, Salted fish & meat, Cheese",
                DemandedGoods: "Wine, Spices, Cloth",
                Wealth: 2),
            new(
                Name: "Braddock",
                House: "Wynch",
                Title: "Baron",
                Holdings: "Direward",
                Description: "A stooped, balding man with thick spectacles, around fifty. Known for loyalty to his wife and a modest, unimposing stature.",
                ProducedGoods: "Cloth, Paper, Ceramics, Dyes",
                DemandedGoods: "Iron, Soft metals, Salt, Leather",
                Wealth: 3),
            new(
                Name: "Brant",
                House: "Slynor",
                Title: "Baron",
                Holdings: "Oakencoast",
                Description: "A coastal baron who watches the oak-lined shore and river mouths. Practical, weather-worn, and more interested in tolls and timber than in Warrington's pageantry.",
                ProducedGoods: "Shipbuilding timber, Flax & hemp, Salted fish & meat, Clay",
                DemandedGoods: "Iron, Salt, Soft metals, Cloth",
                Wealth: 3),
            new(
                Name: "Clarrik",
                House: "Sadelyn",
                Title: "Count",
                Holdings: "Hawk Greeting",
                Description: "A sturdy man with a hard gaze and a proud step. Keeps a rich stud and wields real political weight—his cousin is Archbishop Bedjer Dyernedi, highest priest of Thyrus in the March.",
                ProducedGoods: "Horses, War horses, Noble horses, Leather, Wool, Cheese",
                DemandedGoods: "Iron, Silk, Soft metals, Salt, Spices, Military weapons",
                Wealth: 5),
            new(
                Name: "Colren",
                House: "Warrin",
                Title: "Baron",
                Holdings: "Ilow",
                Description: "A mid-rank Warrin baron of Ilow, careful with words and careful with borders. Rarely seen at great feasts, but his messengers are often in Warrington.",
                ProducedGoods: "Wool, Flax & hemp, Cheese, Clay",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Corlin",
                House: "Werdhog",
                Title: "Baron",
                Holdings: "Klin",
                Description: "The obese baron of Klin. For years he fought Viscount Olgred of Brie, hiring sellswords of doubtful morals who nonetheless helped hold his domain.",
                ProducedGoods: "Leather, Military weapons, Beer, Salted fish & meat",
                DemandedGoods: "Iron, Horses, Salt, Cloth",
                Wealth: 3),
            new(
                Name: "Dalran",
                House: "Spyre",
                Title: "Baron",
                Holdings: "Irtow",
                Description: "Lord of Irtow, a lean holding watched from a tall spyre of stone. Reserved, exacting, and said to know every rumour that crosses his roads.",
                ProducedGoods: "Paper, Soft metals, Glass, Ceramics",
                DemandedGoods: "Spices, Silk, Iron, Cloth",
                Wealth: 3),
            new(
                Name: "Darrin",
                House: "Edgerton",
                Title: "Baron",
                Holdings: "Keatlow",
                Description: "Very ambitious and warlike. His elder brothers died in strange circumstances; after taking power he seized neighbouring lands.",
                ProducedGoods: "Iron, Military weapons, Horses, Leather",
                DemandedGoods: "Salt, Cloth, Soft metals, Wine",
                Wealth: 3),
            new(
                Name: "Dramon",
                House: "Hastwyck",
                Title: "Baron",
                Holdings: "Forestedge",
                Description: "Younger son of Count Keven Hastwyck of Dawntree. Forestedge was carved from Dawntree and granted to him only recently. With a loan from his father and other funds he raised a sizable seat, then—backed by Dawntree's administration—grew the barony quickly and eyed further lands. He sought Hurtbow, but Margrave Hardwin gave it elsewhere. Ambitious and able; rumour says he will not leave his brother's inheritance alone and means to contest Dawntree itself against their father's will.",
                ProducedGoods: "Ironwood, Leather, Honey & wax, Herbs & roots, Building stone",
                DemandedGoods: "Iron, Soft metals, Cloth, Military weapons, Gold",
                Wealth: 3),
            new(
                Name: "Dunna",
                House: "Koltberg",
                Title: "Baronet",
                Holdings: "Holdywag (village)",
                Description: "One of the Koltbergs—a house known for poverty and wildness from the Koltberg hollow. They are little respected and often ignored in Eastern March politics.",
                ProducedGoods: "Building stone, Honey & wax",
                DemandedGoods: "Iron, Cloth",
                Wealth: 1),
            new(
                Name: "Durisug",
                House: "Dag'Thorak",
                Title: "Marquis (Mountain Prince)",
                Holdings: "Groundfall",
                Description: "A hard, unyielding, proud dwarven ruler of a mountain hold. Direct vassal of the Margrave. He has no official say over the March, but his word is respected.",
                ProducedGoods: "Iron, Granite, Soft metals, Dagoferryt, Building stone, Military weapons",
                DemandedGoods: "Wine, Cloth, Salt, Paper, Herbs & roots, Honey & wax",
                Wealth: 5),
            new(
                Name: "Dyron",
                House: "Greatwing",
                Title: "Baron",
                Holdings: "Hurtbow",
                Description: "Tall, thin, and little given to ambition. Known for intelligence and love of learning, logic, and games. Appointed by the Margrave to rule Hurtbow—a troubled barony on the edge of Irredale Forest.",
                ProducedGoods: "Herbs & roots, Honey & wax, Leather, Ironwood",
                DemandedGoods: "Iron, Salt, Military weapons, Soft metals",
                Wealth: 3),
            new(
                Name: "Eldren",
                House: "Morat",
                Title: "Baron",
                Holdings: "Moratz",
                Description: "Baron of Moratz and head of a house that keeps old local rites alongside Imperial law. Soft-spoken in council, stubborn on his own soil.",
                ProducedGoods: "Herbs & roots, Clay, Ceramics, Honey & wax",
                DemandedGoods: "Salt, Cloth, Iron, Paper",
                Wealth: 3),
            new(
                Name: "Erac",
                House: "Mertyn",
                Title: "Count",
                Holdings: "Willow Hill",
                Description: "Loyal vassal of the Margrave. Master of the hunt and protector of the deep woods. Past fifty, still in good fighting shape.",
                ProducedGoods: "Leather, Herbs & roots, Honey & wax, Ironwood, Salted fish & meat",
                DemandedGoods: "Iron, Salt, Wine, Military weapons, Cloth",
                Wealth: 4),
            new(
                Name: "Erwald",
                House: "Clifford",
                Title: "Baron",
                Holdings: "Earthcliff",
                Description: "Twin brother of Parweld, who rules Newcliff. The brothers have been at feud for several years.",
                ProducedGoods: "Wool, Cheese, Flax & hemp, Salted fish & meat",
                DemandedGoods: "Iron, Salt, Military weapons, Cloth",
                Wealth: 3),
            new(
                Name: "Garrel",
                House: "Tudbury",
                Title: "Baron",
                Holdings: "Waterhall",
                Description: "Lord of Waterhall on the river flats. Mild manners hide a keen eye for flood-works, mills, and river tolls.",
                ProducedGoods: "Salted fish & meat, Flax & hemp, Clay, Shipbuilding timber",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Goller",
                House: "von Egglitz",
                Title: "Count",
                Holdings: "Properties in Warrington",
                Description: "A count in title only. Wealthy, a member of Warrington's council, he keeps a small merchant fleet sailing from the Empire as far as Solime, plus lesser ventures.",
                ProducedGoods: "Wine, Cloth, Paper, Amber, Glass, Ceramics",
                DemandedGoods: "Shipbuilding timber, Soft metals, Iron, Spices, Silk, Sugar",
                Wealth: 5),
            new(
                Name: "Graige",
                House: "Oatwright",
                Title: "Baron",
                Holdings: "Darklyn",
                Description: "A grain-and-oats baron of Darklyn, blunt and thrifty. His house thrives on harvest ledgers more than on knightly fame.",
                ProducedGoods: "Wool, Cheese, Flax & hemp, Honey & wax",
                DemandedGoods: "Iron, Salt, Cloth, Soft metals",
                Wealth: 3),
            new(
                Name: "Gron",
                House: "Duevaft",
                Title: "Baron",
                Holdings: "Lonehill",
                Description: "Rules the lonely rise of Lonehill with a small garrison and fewer friends. Suspicious of strangers, loyal to those who keep his roads clear.",
                ProducedGoods: "Honey & wax, Building stone, Herbs & roots, Leather",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Hardwin",
                House: "Greatwing",
                Title: "Margrave",
                Holdings: "Warrington",
                Description: "A sturdy, proud, commanding man of about fifty, full of splendour. Overseer of the triumvirate and unofficial ruler of the Eastern March. A devotee of Thyrus.",
                ProducedGoods: "Wine, Gold, Paper, Glass, Cloth, Horses, Soft metals, Military weapons",
                DemandedGoods: "Spices, War horses, Gemstones, Ivory & walrus bone, Dagoferryt, Olive oil, Sugar, Amber",
                Wealth: 7),
            new(
                Name: "Herrath",
                House: "Highhill",
                Title: "Baron",
                Holdings: "Summerhall",
                Description: "A great man of gentle temper and a love of exotic dishes.",
                ProducedGoods: "Wine, Cheese, Dyes, Salted fish & meat, Cloth",
                DemandedGoods: "Silk, Ivory & walrus bone, Iron, Soft metals, Spices",
                Wealth: 4),
            new(
                Name: "Huel",
                House: "Blackfyre",
                Title: "Baron",
                Holdings: "Gillamoor",
                Description: "Knighted at fourteen after the Battle of the Pass. Through a warlike temper, endurance, and few scruples he won one of the larger domains and armies in the Eastern March.",
                ProducedGoods: "Military weapons, Medium armor, Horses, Iron, Leather",
                DemandedGoods: "Salt, Cloth, Soft metals, Wine, Salted fish & meat",
                Wealth: 4),
            new(
                Name: "Igwar",
                House: "Zorren",
                Title: "Baron",
                Holdings: "Olm",
                Description: "A young, plain-looking youth—little known and of little interest at court.",
                ProducedGoods: "Wool, Clay, Ceramics, Bricks",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Jardan",
                House: "Ferren",
                Title: "Baron",
                Holdings: "Ogrville",
                Description: "Baron of Ogrville on rough border ground. Hard bargainer, harder drinker after victories, and forever short of good iron for his spears.",
                ProducedGoods: "Leather, Military weapons, Honey & wax, Building stone",
                DemandedGoods: "Iron, Salt, Cloth, Soft metals",
                Wealth: 3),
            new(
                Name: "Jerald",
                House: "Grann",
                Title: "Viscount",
                Holdings: "Brodlow",
                Description: "Has fought goblin hordes on his lands for over twenty years and lost two sons to them. Said to hate goblins so fiercely that once, disarmed and surrounded, he tore them apart and gouged out their eyes with his fingers.",
                ProducedGoods: "Horses, Ironwood, Leather, Honey & wax, Military weapons",
                DemandedGoods: "Iron, Salt, Cloth, Soft metals, Medium armor",
                Wealth: 4),
            new(
                Name: "Jorah",
                House: "Parren",
                Title: "Baron",
                Holdings: "Last Inn",
                Description: "A sturdy man in middle years—broad shoulders, thick side-whiskers, and a stern look over a wide, badly set nose. Proud, with an unblemished name. His son and heir Ivern has paralysed legs and cannot walk.",
                ProducedGoods: "Leather, Cheese, Wool, Salted fish & meat",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Keven",
                House: "Hastwyck",
                Title: "Count",
                Holdings: "Dawntree",
                Description: "Count of Dawntree and head of House Hastwyck. He recently carved Forestedge from his own lands and granted it to his younger son Dramon, keeping the elder line's claim on Dawntree. A careful patron: he backed Dramon's new seat with a loan and administrative help, yet remains wary of his son's appetite for further conquest.",
                ProducedGoods: "Ironwood, Honey & wax, Leather, Herbs & roots, Wine, Cloth",
                DemandedGoods: "Iron, Soft metals, Salt, Military weapons, Paper",
                Wealth: 4),
            new(
                Name: "Kyllan",
                House: "Stingryn",
                Title: "Baron",
                Holdings: "Cywell",
                Description: "A sharp-tongued baron of Cywell who collects debts as carefully as he collects insults. Small domain, long memory.",
                ProducedGoods: "Cloth, Soft metals, Dyes, Ceramics",
                DemandedGoods: "Iron, Salt, Silk, Paper",
                Wealth: 3),
            new(
                Name: "Lancion",
                House: "Practor",
                Title: "Count",
                Holdings: "Gray Obelisk",
                Description: "Count of a major trade hub on Warrington's main river. Haughty and corpulent, with a large appetite and a love of gambling.",
                ProducedGoods: "Salt, Ceramics, Cheese, Wool, Flax & hemp, Shipbuilding timber",
                DemandedGoods: "Cloth, Iron, Soft metals, Silk, Spices, Wine",
                Wealth: 5),
            new(
                Name: "Liram",
                House: "Kettleblack",
                Title: "Baron",
                Holdings: "Lorenmill",
                Description: "Keeps the mill-town of Lorenmill running on flour, tolls, and blacksmith smoke. Unflashy, but the bakers and millers of three baronies know his name.",
                ProducedGoods: "Flax & hemp, Cheese, Clay, Bricks",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Lother",
                House: "Whistleblow",
                Title: "Baron",
                Holdings: "Pitchfork",
                Description: "An old, seasoned hand of March politics. Close friend of Marquis Argewald Canterill. Content with life, a loyal vassal, and a lover of every kind of feast.",
                ProducedGoods: "Wine, Cheese, Honey & wax, Salted fish & meat",
                DemandedGoods: "Spices, Silk, Iron, Soft metals",
                Wealth: 3),
            new(
                Name: "Melevan",
                House: "Mirrforge",
                Title: "Viscount",
                Holdings: "Dreton",
                Description: "Viscount of Dreton, where forges and mirror-bright plate make his house's name. Cool in council; hotter when contracts for metal are on the table.",
                ProducedGoods: "Iron, Soft metals, Military weapons, Glass, Medium armor",
                DemandedGoods: "Leather, Cloth, Salt, Wine, Bricks",
                Wealth: 4),
            new(
                Name: "Mevir",
                House: "Darkfrost",
                Title: "Baron",
                Holdings: "Bonefyre",
                Description: "A former Inquisition captain raised to a barony for service and ability.",
                ProducedGoods: "Ironwood, Leather, Herbs & roots, Military weapons",
                DemandedGoods: "Iron, Salt, Cloth, Soft metals",
                Wealth: 3),
            new(
                Name: "Myrton",
                House: "Greyward",
                Title: "Marquis",
                Holdings: "Betforge",
                Description: "Honourable, loyal, and just—a veteran of the Kildrad war. Marquis of the triumvirate. A devotee of Ur.",
                ProducedGoods: "Iron, Soft metals, Military weapons, Bricks, Building stone, Granite",
                DemandedGoods: "Cloth, Wine, Salt, Paper, Leather, Horses",
                Wealth: 5),
            new(
                Name: "Nathar",
                House: "Warrin",
                Title: "Baron",
                Holdings: "Warning Arrow",
                Description: "Handsome and well-groomed, in faultless dress with many touches of wood-elf fashion. Sparing with emotion, but polite.",
                ProducedGoods: "Elven alder, Dyes, Cloth, Herbs & roots, Glass",
                DemandedGoods: "Iron, Soft metals, Salt, Silk, Spices",
                Wealth: 4),
            new(
                Name: "Nowald",
                House: "Greatwing",
                Title: "Baronet",
                Holdings: "Nerton (village by Warrington)",
                Description: "Son of a cousin of Margrave Hardwin Greatwing. A sturdy, tall dark-haired man around thirty. Influential and ambitious.",
                ProducedGoods: "Wine, Cloth, Horses",
                DemandedGoods: "Gold, Spices, Silk",
                Wealth: 2),
            new(
                Name: "Olgred",
                House: "Trur",
                Title: "Viscount",
                Holdings: "Brie",
                Description: "Of Kildrad blood. After his father's death he turned the barony into a military zone and entered a war with Lord Werdhog of Klin that he could not win.",
                ProducedGoods: "Military weapons, Horses, Iron, Leather, Medium armor",
                DemandedGoods: "Salt, Cloth, Soft metals, Wine, Paper",
                Wealth: 4),
            new(
                Name: "Orswal",
                House: "Goodwill",
                Title: "Baron",
                Holdings: "Bearbury",
                Description: "Baron of Bearbury, famed for open hospitality and for hunting bears in the nearby woods. Generous to guests, slow to forgive a slight at his table.",
                ProducedGoods: "Honey & wax, Leather, Salted fish & meat, Ironwood",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Parweld",
                House: "Clifford",
                Title: "Baron",
                Holdings: "Newcliff",
                Description: "Twin brother of Erwald, who rules Earthcliff. The brothers have been at feud for several years.",
                ProducedGoods: "Wool, Cheese, Flax & hemp, Salted fish & meat",
                DemandedGoods: "Iron, Salt, Military weapons, Cloth",
                Wealth: 3),
            new(
                Name: "Payton",
                House: "Highcrow",
                Title: "Viscount",
                Holdings: "Northlap",
                Description: "Lord of a foothill settlement ringed by wild western forests. Watches the western border and the Edge Mountains. Rumours tie his house to witches.",
                ProducedGoods: "Herbs & roots, Honey & wax, Ironwood, Leather, Building stone",
                DemandedGoods: "Iron, Salt, Cloth, Soft metals, Wine",
                Wealth: 4),
            new(
                Name: "Piff",
                House: "Hogger",
                Title: "Baron",
                Holdings: "Hogbridge",
                Description: "Fourth son of Lord Ogwal (the three before him died in strange circumstances). Massive, fat, strong, and foul-smelling. Looks duller than he is.",
                ProducedGoods: "Leather, Salted fish & meat, Wool, Clay",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Pranar",
                House: "Cheswright",
                Title: "Baron",
                Holdings: "Lafast",
                Description: "An elderly baron of a noble house. True to his word, honourable, and proud. Known for sense, caution, and choosing good people.",
                ProducedGoods: "Cheese, Cloth, Horses, Wine",
                DemandedGoods: "Iron, Soft metals, Salt, Military weapons",
                Wealth: 3),
            new(
                Name: "Ruger",
                House: "Lydden",
                Title: "Baron",
                Holdings: "Fillbury",
                Description: "A practical Fillbury baron who minds orchards, bridges, and market days. Avoids open feuds; settles most quarrels with coin or a quiet favour.",
                ProducedGoods: "Honey & wax, Cheese, Flax & hemp, Dyes",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Ryher",
                House: "Tarwin",
                Title: "Baron",
                Holdings: "Bredow",
                Description: "Started a conflict with the Vorgowelds that turned a prosperous trading domain into a war-torn, militarised ruin.",
                ProducedGoods: "Military weapons, Iron, Leather, Cloth",
                DemandedGoods: "Salt, Soft metals, Wine, Spices",
                Wealth: 3),
            new(
                Name: "Sulvan",
                House: "Tarpp",
                Title: "Baron",
                Holdings: "Timberhill",
                Description: "A huge man of great strength and fighting skill. Oddly known for a gentle nature and a love of animals.",
                ProducedGoods: "Ironwood, Honey & wax, Leather, Herbs & roots",
                DemandedGoods: "Iron, Cloth, Salt, Soft metals",
                Wealth: 3),
            new(
                Name: "Thaddeus",
                House: "Direbolt",
                Title: "Baron",
                Holdings: "Darkhold",
                Description: "A decorated general and veteran of the war against the lizardfolk, come from deep in the Empire. Of a significant, wealthy, honourable family.",
                ProducedGoods: "Military weapons, Medium armor, Horses, Iron, Leather",
                DemandedGoods: "Wine, Cloth, Salt, Soft metals, Paper",
                Wealth: 4),
            new(
                Name: "Tirus",
                House: "Donniger",
                Title: "Viscount",
                Holdings: "Madtree",
                Description: "Viscount of Madtree, where twisted old oaks and odd local rites keep travellers wary. Dry humour, sharp ledgers, and little patience for superstition—unless it pays.",
                ProducedGoods: "Herbs & roots, Honey & wax, Paper, Ironwood, Dyes",
                DemandedGoods: "Iron, Salt, Cloth, Soft metals, Wine",
                Wealth: 4),
            new(
                Name: "Turen",
                House: "Koltberg",
                Title: "Baronet",
                Holdings: "Um (village)",
                Description: "One of the Koltbergs—a house known for poverty and wildness from the Koltberg hollow. They are little respected and often ignored in Eastern March politics.",
                ProducedGoods: "Building stone, Honey & wax",
                DemandedGoods: "Iron, Cloth",
                Wealth: 1),
            new(
                Name: "Urven",
                House: "Blackward",
                Title: "Baron",
                Holdings: "Orlyn",
                Description: "A legitimised bastard of a Greyward cadet line, distant kin to Myrton. An adroit, merciful ruler who minds his subjects' welfare. Organiser of the \"Royal Hunts\", very popular among the elite.",
                ProducedGoods: "Ironwood, Herbs & roots, Honey & wax, Leather, Dyes",
                DemandedGoods: "Iron, Salt, Cloth, Soft metals, Wine",
                Wealth: 4),
            new(
                Name: "Virrol",
                House: "Lonetower",
                Title: "Viscount",
                Holdings: "Zinth",
                Description: "Warm, kind, and intelligent, though of frail build and rather timid. Even so, a good steward of quite prosperous Zinth.",
                ProducedGoods: "Glass, Cloth, Cheese, Paper, Ceramics",
                DemandedGoods: "Iron, Soft metals, Salt, Silk, Spices",
                Wealth: 4),
            new(
                Name: "Volenbert",
                House: "Oxenverd",
                Title: "Baronet",
                Holdings: "Lands by Warrington",
                Description: "An older man who recently lost his daughter Vivienne.",
                ProducedGoods: "Cloth, Cheese, Wine",
                DemandedGoods: "Spices, Silk, Gold",
                Wealth: 2),
            new(
                Name: "Vortigern",
                House: "Blackhammer",
                Title: "Baron",
                Holdings: "Blackhammer",
                Description: "Newly raised lord of Blackhammer Valley. A former mercenary with a murky past and a reputation as a capable, resourceful fighter.",
                ProducedGoods: "Building stone, Iron, Soft metals, Granite",
                DemandedGoods: "Leather, Cloth, Salt, Military weapons",
                Wealth: 3),
            new(
                Name: "Welron",
                House: "Sprentrack",
                Title: "Enforest",
                Holdings: "Redpine",
                Description: "Holder of the Enforest title over Redpine woods—ranger-lord more than courtier. Knows every game trail and every outlaw camp under the red pines.",
                ProducedGoods: "Ironwood, Herbs & roots, Honey & wax, Leather",
                DemandedGoods: "Iron, Salt, Cloth, Soft metals",
                Wealth: 3),
            new(
                Name: "Will the Stammerer",
                House: "Koltberg",
                Title: "Baronet",
                Holdings: "Arg (village)",
                Description: "One of the Koltbergs—a house known for poverty and wildness from the Koltberg hollow. They are little respected and often ignored in Eastern March politics.",
                ProducedGoods: "Building stone, Honey & wax",
                DemandedGoods: "Iron, Cloth",
                Wealth: 1),
            new(
                Name: "Yagga",
                House: "Wildberry",
                Title: "Baroness",
                Holdings: "Borolin",
                Description: "An old house from Kilgrad days. At its head stands young, beautiful, warlike Yagga, whose looks are matched only by the force of her temper.",
                ProducedGoods: "Horses, Military weapons, Leather, Ironwood",
                DemandedGoods: "Iron, Wine, Salt, Cloth",
                Wealth: 3),
        };
    }
}
