/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_WAKEUP_WAKEUPREQUEST_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_WAKEUP_WAKEUPREQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _remote_control_WakeUpRequest_Reason { 
    remote_control_WakeUpRequest_Reason_REASON_UNDEFINED = 0, 
    remote_control_WakeUpRequest_Reason_REASON_INFOTAINMENT_SYSTEM = 1, 
    remote_control_WakeUpRequest_Reason_REASON_CHARGING_SCENARIO_0 = 2, 
    remote_control_WakeUpRequest_Reason_REASON_CHARGING_SCENARIO_1 = 3, 
    remote_control_WakeUpRequest_Reason_REASON_CHARGING_SCENARIO_2 = 4, 
    remote_control_WakeUpRequest_Reason_REASON_CHARGING_SCENARIO_3 = 5, 
    remote_control_WakeUpRequest_Reason_REASON_CHARGING_SCENARIO_4 = 6 
} remote_control_WakeUpRequest_Reason;

typedef enum _remote_control_WakeUpRequest_Resource { 
    remote_control_WakeUpRequest_Resource_RESOURCE_UNSPECIFIED = 0, 
    remote_control_WakeUpRequest_Resource_RESOURCE_INFOTAINMENT = 1, 
    remote_control_WakeUpRequest_Resource_RESOURCE_CORE_SYSTEM = 2 
} remote_control_WakeUpRequest_Resource;

/* Struct definitions */
typedef struct _remote_control_WakeUpRequest { 
    remote_control_WakeUpRequest_Reason reason; 
    uint32_t keep_awake_duration; /* time in seconds */
    pb_callback_t resource; 
} remote_control_WakeUpRequest;


/* Helper constants for enums */
#define _remote_control_WakeUpRequest_Reason_MIN remote_control_WakeUpRequest_Reason_REASON_UNDEFINED
#define _remote_control_WakeUpRequest_Reason_MAX remote_control_WakeUpRequest_Reason_REASON_CHARGING_SCENARIO_4
#define _remote_control_WakeUpRequest_Reason_ARRAYSIZE ((remote_control_WakeUpRequest_Reason)(remote_control_WakeUpRequest_Reason_REASON_CHARGING_SCENARIO_4+1))

#define _remote_control_WakeUpRequest_Resource_MIN remote_control_WakeUpRequest_Resource_RESOURCE_UNSPECIFIED
#define _remote_control_WakeUpRequest_Resource_MAX remote_control_WakeUpRequest_Resource_RESOURCE_CORE_SYSTEM
#define _remote_control_WakeUpRequest_Resource_ARRAYSIZE ((remote_control_WakeUpRequest_Resource)(remote_control_WakeUpRequest_Resource_RESOURCE_CORE_SYSTEM+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_WakeUpRequest_init_default {_remote_control_WakeUpRequest_Reason_MIN, 0, {{NULL}, NULL}}
#define remote_control_WakeUpRequest_init_zero   {_remote_control_WakeUpRequest_Reason_MIN, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_WakeUpRequest_reason_tag  1
#define remote_control_WakeUpRequest_keep_awake_duration_tag 2
#define remote_control_WakeUpRequest_resource_tag 3

/* Struct field encoding specification for nanopb */
#define remote_control_WakeUpRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            1) \
X(a, STATIC,   SINGULAR, UINT32,   keep_awake_duration,   2) \
X(a, CALLBACK, REPEATED, UENUM,    resource,          3)
#define remote_control_WakeUpRequest_CALLBACK pb_default_field_callback
#define remote_control_WakeUpRequest_DEFAULT NULL

extern const pb_msgdesc_t remote_control_WakeUpRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_WakeUpRequest_fields &remote_control_WakeUpRequest_msg

/* Maximum encoded size of messages (where known) */
/* remote_control_WakeUpRequest_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
