/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_STATUS_ENTITIES_OTAMODE_OTAINSTALLATIONSTATUS_PB_H_INCLUDED
#define PB_STATUS_ENTITIES_OTAMODE_OTAINSTALLATIONSTATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _status_OTAInstallationStatusValue { 
    status_OTAInstallationStatusValue_OTA_INSTALLATION_STATUS_VALUE_UNKNOWN = 0, 
    status_OTAInstallationStatusValue_OTA_INSTALLATION_STATUS_VALUE_INSTALLATION_COMPLETED = 1, 
    status_OTAInstallationStatusValue_OTA_INSTALLATION_STATUS_VALUE_INSTALLATION_STARTED = 2 
} status_OTAInstallationStatusValue;

/* Struct definitions */
typedef struct _status_OTAInstallationStatus { 
    status_OTAInstallationStatusValue ota_installation_status; 
} status_OTAInstallationStatus;


/* Helper constants for enums */
#define _status_OTAInstallationStatusValue_MIN status_OTAInstallationStatusValue_OTA_INSTALLATION_STATUS_VALUE_UNKNOWN
#define _status_OTAInstallationStatusValue_MAX status_OTAInstallationStatusValue_OTA_INSTALLATION_STATUS_VALUE_INSTALLATION_STARTED
#define _status_OTAInstallationStatusValue_ARRAYSIZE ((status_OTAInstallationStatusValue)(status_OTAInstallationStatusValue_OTA_INSTALLATION_STATUS_VALUE_INSTALLATION_STARTED+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define status_OTAInstallationStatus_init_default {_status_OTAInstallationStatusValue_MIN}
#define status_OTAInstallationStatus_init_zero   {_status_OTAInstallationStatusValue_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define status_OTAInstallationStatus_ota_installation_status_tag 1

/* Struct field encoding specification for nanopb */
#define status_OTAInstallationStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    ota_installation_status,   1)
#define status_OTAInstallationStatus_CALLBACK NULL
#define status_OTAInstallationStatus_DEFAULT NULL

extern const pb_msgdesc_t status_OTAInstallationStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define status_OTAInstallationStatus_fields &status_OTAInstallationStatus_msg

/* Maximum encoded size of messages (where known) */
#define status_OTAInstallationStatus_size        2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
