/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_PARKING_CLIMATIZATION_TIMERS_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_PARKING_CLIMATIZATION_TIMERS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _remote_control_TimerState {
    remote_control_TimerState_TIMER_STATE_UNSPECIFIED = 0,
    remote_control_TimerState_TIMER_STATE_OFF = 1,
    remote_control_TimerState_TIMER_STATE_ON = 2,
    remote_control_TimerState_TIMER_STATE_NOT_SET = 3
} remote_control_TimerState;

typedef enum _remote_control_YesNoDone {
    remote_control_YesNoDone_YES_NO_DONE_UNSPECIFIED = 0,
    remote_control_YesNoDone_YES_NO_DONE_NO = 1,
    remote_control_YesNoDone_YES_NO_DONE_YES = 2,
    remote_control_YesNoDone_YES_NO_DONE_DONE = 3
} remote_control_YesNoDone;

typedef enum _remote_control_ParkingClimatizationTimerIndex {
    remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_UNSPECIFIED = 0,
    remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_0 = 1,
    remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_1 = 2,
    remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_2 = 3,
    remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_3 = 4,
    remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_4 = 5,
    remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_5 = 6,
    remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_6 = 7,
    remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_7 = 8
} remote_control_ParkingClimatizationTimerIndex;

/* Struct definitions */
typedef struct _remote_control_GetParkingClimatizationTimerListRequest {
    char dummy_field;
} remote_control_GetParkingClimatizationTimerListRequest;

typedef struct _remote_control_ParkingClimatizationTimerList {
    remote_control_ParkingClimatizationTimerIndex next_active_timer;
    pb_callback_t parking_climate_timer_objects;
} remote_control_ParkingClimatizationTimerList;

typedef struct _remote_control_ParkingClimatizationTimerSchedule {
    remote_control_YesNoDone run_on_day_0;
    remote_control_YesNoDone run_on_day_1;
    remote_control_YesNoDone run_on_day_2;
    remote_control_YesNoDone run_on_day_3;
    remote_control_YesNoDone run_on_day_4;
    remote_control_YesNoDone run_on_day_5;
    remote_control_YesNoDone run_on_day_6;
} remote_control_ParkingClimatizationTimerSchedule;

typedef struct _remote_control_SetParkingClimatizationTimerListResponse {
    uint32_t status_code;
} remote_control_SetParkingClimatizationTimerListResponse;

typedef struct _remote_control_GetParkingClimatizationTimerListResponse {
    bool has_timer_list;
    remote_control_ParkingClimatizationTimerList timer_list;
} remote_control_GetParkingClimatizationTimerListResponse;

typedef struct _remote_control_ParkingClimatizationTimerListUpdate {
    bool has_timer_list;
    remote_control_ParkingClimatizationTimerList timer_list;
} remote_control_ParkingClimatizationTimerListUpdate;

typedef struct _remote_control_ParkingClimatizationTimerObject {
    remote_control_TimerState timer_state;
    uint32_t completion_time_minutes_after_midnight;
    bool repeat_timer;
    bool has_timer_schedule;
    remote_control_ParkingClimatizationTimerSchedule timer_schedule;
} remote_control_ParkingClimatizationTimerObject;

typedef struct _remote_control_SetParkingClimatizationTimerListRequest {
    bool has_timer_list;
    remote_control_ParkingClimatizationTimerList timer_list;
} remote_control_SetParkingClimatizationTimerListRequest;


/* Helper constants for enums */
#define _remote_control_TimerState_MIN remote_control_TimerState_TIMER_STATE_UNSPECIFIED
#define _remote_control_TimerState_MAX remote_control_TimerState_TIMER_STATE_NOT_SET
#define _remote_control_TimerState_ARRAYSIZE ((remote_control_TimerState)(remote_control_TimerState_TIMER_STATE_NOT_SET+1))

#define _remote_control_YesNoDone_MIN remote_control_YesNoDone_YES_NO_DONE_UNSPECIFIED
#define _remote_control_YesNoDone_MAX remote_control_YesNoDone_YES_NO_DONE_DONE
#define _remote_control_YesNoDone_ARRAYSIZE ((remote_control_YesNoDone)(remote_control_YesNoDone_YES_NO_DONE_DONE+1))

#define _remote_control_ParkingClimatizationTimerIndex_MIN remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_UNSPECIFIED
#define _remote_control_ParkingClimatizationTimerIndex_MAX remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_7
#define _remote_control_ParkingClimatizationTimerIndex_ARRAYSIZE ((remote_control_ParkingClimatizationTimerIndex)(remote_control_ParkingClimatizationTimerIndex_PARKING_CLIMATIZATION_TIMER_7+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_ParkingClimatizationTimerSchedule_init_default {_remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN}
#define remote_control_ParkingClimatizationTimerObject_init_default {_remote_control_TimerState_MIN, 0, 0, false, remote_control_ParkingClimatizationTimerSchedule_init_default}
#define remote_control_ParkingClimatizationTimerList_init_default {_remote_control_ParkingClimatizationTimerIndex_MIN, {{NULL}, NULL}}
#define remote_control_SetParkingClimatizationTimerListRequest_init_default {false, remote_control_ParkingClimatizationTimerList_init_default}
#define remote_control_SetParkingClimatizationTimerListResponse_init_default {0}
#define remote_control_GetParkingClimatizationTimerListRequest_init_default {0}
#define remote_control_GetParkingClimatizationTimerListResponse_init_default {false, remote_control_ParkingClimatizationTimerList_init_default}
#define remote_control_ParkingClimatizationTimerListUpdate_init_default {false, remote_control_ParkingClimatizationTimerList_init_default}
#define remote_control_ParkingClimatizationTimerSchedule_init_zero {_remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN, _remote_control_YesNoDone_MIN}
#define remote_control_ParkingClimatizationTimerObject_init_zero {_remote_control_TimerState_MIN, 0, 0, false, remote_control_ParkingClimatizationTimerSchedule_init_zero}
#define remote_control_ParkingClimatizationTimerList_init_zero {_remote_control_ParkingClimatizationTimerIndex_MIN, {{NULL}, NULL}}
#define remote_control_SetParkingClimatizationTimerListRequest_init_zero {false, remote_control_ParkingClimatizationTimerList_init_zero}
#define remote_control_SetParkingClimatizationTimerListResponse_init_zero {0}
#define remote_control_GetParkingClimatizationTimerListRequest_init_zero {0}
#define remote_control_GetParkingClimatizationTimerListResponse_init_zero {false, remote_control_ParkingClimatizationTimerList_init_zero}
#define remote_control_ParkingClimatizationTimerListUpdate_init_zero {false, remote_control_ParkingClimatizationTimerList_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_ParkingClimatizationTimerList_next_active_timer_tag 1
#define remote_control_ParkingClimatizationTimerList_parking_climate_timer_objects_tag 2
#define remote_control_ParkingClimatizationTimerSchedule_run_on_day_0_tag 1
#define remote_control_ParkingClimatizationTimerSchedule_run_on_day_1_tag 2
#define remote_control_ParkingClimatizationTimerSchedule_run_on_day_2_tag 3
#define remote_control_ParkingClimatizationTimerSchedule_run_on_day_3_tag 4
#define remote_control_ParkingClimatizationTimerSchedule_run_on_day_4_tag 5
#define remote_control_ParkingClimatizationTimerSchedule_run_on_day_5_tag 6
#define remote_control_ParkingClimatizationTimerSchedule_run_on_day_6_tag 7
#define remote_control_SetParkingClimatizationTimerListResponse_status_code_tag 1
#define remote_control_GetParkingClimatizationTimerListResponse_timer_list_tag 1
#define remote_control_ParkingClimatizationTimerListUpdate_timer_list_tag 1
#define remote_control_ParkingClimatizationTimerObject_timer_state_tag 1
#define remote_control_ParkingClimatizationTimerObject_completion_time_minutes_after_midnight_tag 2
#define remote_control_ParkingClimatizationTimerObject_repeat_timer_tag 3
#define remote_control_ParkingClimatizationTimerObject_timer_schedule_tag 4
#define remote_control_SetParkingClimatizationTimerListRequest_timer_list_tag 1

/* Struct field encoding specification for nanopb */
#define remote_control_ParkingClimatizationTimerSchedule_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    run_on_day_0,      1) \
X(a, STATIC,   SINGULAR, UENUM,    run_on_day_1,      2) \
X(a, STATIC,   SINGULAR, UENUM,    run_on_day_2,      3) \
X(a, STATIC,   SINGULAR, UENUM,    run_on_day_3,      4) \
X(a, STATIC,   SINGULAR, UENUM,    run_on_day_4,      5) \
X(a, STATIC,   SINGULAR, UENUM,    run_on_day_5,      6) \
X(a, STATIC,   SINGULAR, UENUM,    run_on_day_6,      7)
#define remote_control_ParkingClimatizationTimerSchedule_CALLBACK NULL
#define remote_control_ParkingClimatizationTimerSchedule_DEFAULT NULL

#define remote_control_ParkingClimatizationTimerObject_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    timer_state,       1) \
X(a, STATIC,   SINGULAR, UINT32,   completion_time_minutes_after_midnight,   2) \
X(a, STATIC,   SINGULAR, BOOL,     repeat_timer,      3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timer_schedule,    4)
#define remote_control_ParkingClimatizationTimerObject_CALLBACK NULL
#define remote_control_ParkingClimatizationTimerObject_DEFAULT NULL
#define remote_control_ParkingClimatizationTimerObject_timer_schedule_MSGTYPE remote_control_ParkingClimatizationTimerSchedule

#define remote_control_ParkingClimatizationTimerList_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    next_active_timer,   1) \
X(a, CALLBACK, REPEATED, MESSAGE,  parking_climate_timer_objects,   2)
#define remote_control_ParkingClimatizationTimerList_CALLBACK pb_default_field_callback
#define remote_control_ParkingClimatizationTimerList_DEFAULT NULL
#define remote_control_ParkingClimatizationTimerList_parking_climate_timer_objects_MSGTYPE remote_control_ParkingClimatizationTimerObject

#define remote_control_SetParkingClimatizationTimerListRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timer_list,        1)
#define remote_control_SetParkingClimatizationTimerListRequest_CALLBACK NULL
#define remote_control_SetParkingClimatizationTimerListRequest_DEFAULT NULL
#define remote_control_SetParkingClimatizationTimerListRequest_timer_list_MSGTYPE remote_control_ParkingClimatizationTimerList

#define remote_control_SetParkingClimatizationTimerListResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status_code,       1)
#define remote_control_SetParkingClimatizationTimerListResponse_CALLBACK NULL
#define remote_control_SetParkingClimatizationTimerListResponse_DEFAULT NULL

#define remote_control_GetParkingClimatizationTimerListRequest_FIELDLIST(X, a) \

#define remote_control_GetParkingClimatizationTimerListRequest_CALLBACK NULL
#define remote_control_GetParkingClimatizationTimerListRequest_DEFAULT NULL

#define remote_control_GetParkingClimatizationTimerListResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timer_list,        1)
#define remote_control_GetParkingClimatizationTimerListResponse_CALLBACK NULL
#define remote_control_GetParkingClimatizationTimerListResponse_DEFAULT NULL
#define remote_control_GetParkingClimatizationTimerListResponse_timer_list_MSGTYPE remote_control_ParkingClimatizationTimerList

#define remote_control_ParkingClimatizationTimerListUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timer_list,        1)
#define remote_control_ParkingClimatizationTimerListUpdate_CALLBACK NULL
#define remote_control_ParkingClimatizationTimerListUpdate_DEFAULT NULL
#define remote_control_ParkingClimatizationTimerListUpdate_timer_list_MSGTYPE remote_control_ParkingClimatizationTimerList

extern const pb_msgdesc_t remote_control_ParkingClimatizationTimerSchedule_msg;
extern const pb_msgdesc_t remote_control_ParkingClimatizationTimerObject_msg;
extern const pb_msgdesc_t remote_control_ParkingClimatizationTimerList_msg;
extern const pb_msgdesc_t remote_control_SetParkingClimatizationTimerListRequest_msg;
extern const pb_msgdesc_t remote_control_SetParkingClimatizationTimerListResponse_msg;
extern const pb_msgdesc_t remote_control_GetParkingClimatizationTimerListRequest_msg;
extern const pb_msgdesc_t remote_control_GetParkingClimatizationTimerListResponse_msg;
extern const pb_msgdesc_t remote_control_ParkingClimatizationTimerListUpdate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_ParkingClimatizationTimerSchedule_fields &remote_control_ParkingClimatizationTimerSchedule_msg
#define remote_control_ParkingClimatizationTimerObject_fields &remote_control_ParkingClimatizationTimerObject_msg
#define remote_control_ParkingClimatizationTimerList_fields &remote_control_ParkingClimatizationTimerList_msg
#define remote_control_SetParkingClimatizationTimerListRequest_fields &remote_control_SetParkingClimatizationTimerListRequest_msg
#define remote_control_SetParkingClimatizationTimerListResponse_fields &remote_control_SetParkingClimatizationTimerListResponse_msg
#define remote_control_GetParkingClimatizationTimerListRequest_fields &remote_control_GetParkingClimatizationTimerListRequest_msg
#define remote_control_GetParkingClimatizationTimerListResponse_fields &remote_control_GetParkingClimatizationTimerListResponse_msg
#define remote_control_ParkingClimatizationTimerListUpdate_fields &remote_control_ParkingClimatizationTimerListUpdate_msg

/* Maximum encoded size of messages (where known) */
/* remote_control_ParkingClimatizationTimerList_size depends on runtime parameters */
/* remote_control_SetParkingClimatizationTimerListRequest_size depends on runtime parameters */
/* remote_control_GetParkingClimatizationTimerListResponse_size depends on runtime parameters */
/* remote_control_ParkingClimatizationTimerListUpdate_size depends on runtime parameters */
#define remote_control_GetParkingClimatizationTimerListRequest_size 0
#define remote_control_ParkingClimatizationTimerObject_size 26
#define remote_control_ParkingClimatizationTimerSchedule_size 14
#define remote_control_SetParkingClimatizationTimerListResponse_size 6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
