/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_ENTITIES_BATTERYCHARGE_CHARGECONTROLSTATUS_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_ENTITIES_BATTERYCHARGE_CHARGECONTROLSTATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _remote_control_ChargeControlStatus { 
    remote_control_ChargeControlStatus_CHARGE_CONTROL_STATUS_UNSPECIFIED = 0, 
    remote_control_ChargeControlStatus_CHARGE_CONTROL_STATUS_CHARGING_TOWARDS_MIN_SOC = 1, 
    remote_control_ChargeControlStatus_CHARGE_CONTROL_STATUS_MANUAL_PLUG_IN_CHARGING = 2, 
    remote_control_ChargeControlStatus_CHARGE_CONTROL_STATUS_MANUAL_SCHEDULE_CHARGING = 3, 
    remote_control_ChargeControlStatus_CHARGE_CONTROL_STATUS_SMART_CHARGING = 4, 
    remote_control_ChargeControlStatus_CHARGE_CONTROL_STATUS_CHARGE_NOW = 5 
} remote_control_ChargeControlStatus;

/* Helper constants for enums */
#define _remote_control_ChargeControlStatus_MIN remote_control_ChargeControlStatus_CHARGE_CONTROL_STATUS_UNSPECIFIED
#define _remote_control_ChargeControlStatus_MAX remote_control_ChargeControlStatus_CHARGE_CONTROL_STATUS_CHARGE_NOW
#define _remote_control_ChargeControlStatus_ARRAYSIZE ((remote_control_ChargeControlStatus)(remote_control_ChargeControlStatus_CHARGE_CONTROL_STATUS_CHARGE_NOW+1))


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
