using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DA_Scribe.Entities
{
    /// <summary>
    /// Core memory unit - extracted and processed content from campaigns.
    /// This is the main entity that represents a piece of knowledge in SCRIBE.
    /// </summary>
    public class ScribeMemory
    {
        [Key]
        public int Id { get; set; }
        
        /// <summary>
        /// Title of the memory, e.g., "Garrick meets the Black Dragon"
        /// </summary>
        [Required]
        [MaxLength(500)]
        public string Title { get; set; } = string.Empty;
        
        /// <summary>
        /// Full processed text content
        /// </summary>
        [Required]
        public string Content { get; set; } = string.Empty;
        
        /// <summary>
        /// Type classification of the memory
        /// </summary>
        public MemoryType Type { get; set; } = MemoryType.Event;
        
        /// <summary>
        /// When this memory was created in SCRIBE
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        
        /// <summary>
        /// When this memory was last updated
        /// </summary>
        public DateTime? UpdatedAt { get; set; }
        
        // Source tracking - where did this memory come from?
        
        /// <summary>
        /// If extracted from a post, the source post ID
        /// </summary>
        public int? SourcePostId { get; set; }
        
        /// <summary>
        /// If related to a specific chapter
        /// </summary>
        public int? SourceChapterId { get; set; }
        
        /// <summary>
        /// The campaign this memory belongs to
        /// </summary>
        public int? SourceCampaignId { get; set; }
        
        /// <summary>
        /// Original document filename (for imported .docx files)
        /// </summary>
        [MaxLength(500)]
        public string? SourceDocumentName { get; set; }
        
        // Access control
        
        /// <summary>
        /// IDs of characters who "know" this memory (for access control).
        /// Stored as comma-separated values for simplicity.
        /// </summary>
        [MaxLength(1000)]
        public string? CharacterIdsJson { get; set; }
        
        /// <summary>
        /// If true, all players can access this memory regardless of character involvement
        /// </summary>
        public bool IsPublic { get; set; } = false;
        
        /// <summary>
        /// If true, only GM can see this memory
        /// </summary>
        public bool IsGmOnly { get; set; } = false;
        
        // LLM generation metadata
        
        /// <summary>
        /// If true, this memory was generated by an LLM (e.g., summary)
        /// </summary>
        public bool IsGenerated { get; set; } = false;
        
        /// <summary>
        /// Name of the model that generated this memory
        /// </summary>
        [MaxLength(100)]
        public string? GeneratedByModel { get; set; }
        
        // Navigation
        
        /// <summary>
        /// Chunks of this memory with embeddings for vector search
        /// </summary>
        public virtual ICollection<ScribeChunk> Chunks { get; set; } = new List<ScribeChunk>();
        
        // Helper methods
        
        /// <summary>
        /// Get character IDs that have access to this memory
        /// </summary>
        [NotMapped]
        public IEnumerable<int> CharacterIds
        {
            get
            {
                if (string.IsNullOrEmpty(CharacterIdsJson))
                    return Enumerable.Empty<int>();
                
                return CharacterIdsJson
                    .Split(',', StringSplitOptions.RemoveEmptyEntries)
                    .Select(s => int.TryParse(s.Trim(), out var id) ? id : 0)
                    .Where(id => id > 0);
            }
            set
            {
                CharacterIdsJson = value?.Any() == true 
                    ? string.Join(",", value) 
                    : null;
            }
        }
    }
}
