using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260723010000_BaronLetterThreads")]
    public partial class BaronLetterThreads : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronLetterThreads" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Title" text NOT NULL DEFAULT '',
                    "RelationId" integer NULL,
                    "CorrespondentName" text NOT NULL DEFAULT '',
                    "CorrespondentTitle" text NULL,
                    "CorrespondentCategory" text NULL,
                    "ReplyRegion" text NOT NULL DEFAULT 'Eastern March',
                    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW()
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronLetterThreads_BaronyId"
                    ON "BaronLetterThreads" ("BaronyId");

                CREATE INDEX IF NOT EXISTS "IX_BaronLetterThreads_RelationId"
                    ON "BaronLetterThreads" ("RelationId");

                CREATE TABLE IF NOT EXISTS "BaronLetterMessages" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ThreadId" integer NOT NULL,
                    "BodyHtml" text NOT NULL DEFAULT '',
                    "Status" text NOT NULL DEFAULT 'Draft',
                    "IsInbound" boolean NOT NULL DEFAULT FALSE,
                    "TurnNumber" integer NOT NULL DEFAULT 1,
                    "Year" integer NOT NULL DEFAULT 625,
                    "Month" integer NOT NULL DEFAULT 1,
                    "Season" text NOT NULL DEFAULT 'Winter',
                    "SeenByBaron" boolean NOT NULL DEFAULT TRUE,
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "SentAtUtc" timestamp without time zone NULL,
                    CONSTRAINT "FK_BaronLetterMessages_Threads"
                        FOREIGN KEY ("ThreadId") REFERENCES "BaronLetterThreads" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronLetterMessages_ThreadId"
                    ON "BaronLetterMessages" ("ThreadId");

                -- Migrate legacy BaronLetters → threads (grouped by barony + correspondent + subject) + messages.
                DO $$
                BEGIN
                    IF to_regclass('"BaronLetters"') IS NULL THEN
                        RETURN;
                    END IF;

                    CREATE TEMP TABLE _letter_groups ON COMMIT DROP AS
                    SELECT
                        MIN(l."Id") AS seed_id,
                        l."BaronyId",
                        COALESCE(NULLIF(TRIM(l."Subject"), ''), '(no subject)') AS title,
                        l."RelationId",
                        COALESCE(NULLIF(TRIM(l."RecipientName"), ''), 'Unknown') AS correspondent_name,
                        MAX(l."RecipientTitle") AS correspondent_title,
                        MAX(l."RecipientCategory") AS correspondent_category,
                        COALESCE(MAX(l."ReplyRegion"), 'Eastern March') AS reply_region,
                        MIN(l."CreatedAtUtc") AS created_at,
                        MAX(l."UpdatedAtUtc") AS updated_at,
                        COALESCE(l."RelationId"::text, lower(trim(l."RecipientName")))
                            || '|' || lower(trim(COALESCE(l."Subject", ''))) AS grp
                    FROM "BaronLetters" l
                    GROUP BY
                        l."BaronyId",
                        l."RelationId",
                        lower(trim(l."RecipientName")),
                        lower(trim(COALESCE(l."Subject", ''))),
                        COALESCE(NULLIF(TRIM(l."Subject"), ''), '(no subject)'),
                        COALESCE(NULLIF(TRIM(l."RecipientName"), ''), 'Unknown');

                    CREATE TEMP TABLE _thread_map (
                        grp text PRIMARY KEY,
                        thread_id integer NOT NULL
                    ) ON COMMIT DROP;

                    INSERT INTO "BaronLetterThreads" (
                        "BaronyId", "Title", "RelationId", "CorrespondentName",
                        "CorrespondentTitle", "CorrespondentCategory", "ReplyRegion",
                        "CreatedAtUtc", "UpdatedAtUtc"
                    )
                    SELECT
                        g."BaronyId", g.title, g."RelationId", g.correspondent_name,
                        g.correspondent_title, g.correspondent_category, g.reply_region,
                        g.created_at, g.updated_at
                    FROM _letter_groups g
                    ORDER BY g.seed_id;

                    INSERT INTO _thread_map (grp, thread_id)
                    SELECT g.grp, t."Id"
                    FROM _letter_groups g
                    JOIN "BaronLetterThreads" t
                      ON t."BaronyId" = g."BaronyId"
                     AND t."Title" = g.title
                     AND COALESCE(t."RelationId", -1) = COALESCE(g."RelationId", -1)
                     AND lower(trim(t."CorrespondentName")) = lower(trim(g.correspondent_name));

                    INSERT INTO "BaronLetterMessages" (
                        "ThreadId", "BodyHtml", "Status", "IsInbound",
                        "TurnNumber", "Year", "Month", "Season",
                        "SeenByBaron", "SortOrder",
                        "CreatedAtUtc", "UpdatedAtUtc", "SentAtUtc"
                    )
                    SELECT
                        m.thread_id,
                        COALESCE(l."BodyHtml", ''),
                        COALESCE(l."Status", 'Draft'),
                        COALESCE(l."IsInbound", FALSE),
                        COALESCE(l."TurnNumber", 1),
                        COALESCE(l."Year", 625),
                        COALESCE(l."Month", 1),
                        COALESCE(l."Season", 'Winter'),
                        COALESCE(l."ReplySeenByBaron", TRUE),
                        COALESCE(l."SortOrder", 0),
                        l."CreatedAtUtc",
                        l."UpdatedAtUtc",
                        l."SentAtUtc"
                    FROM "BaronLetters" l
                    JOIN _thread_map m ON m.grp =
                        COALESCE(l."RelationId"::text, lower(trim(l."RecipientName")))
                        || '|' || lower(trim(COALESCE(l."Subject", '')))
                    ORDER BY l."Id";

                    -- Legacy ReplyHtml → separate inbound delivered message.
                    INSERT INTO "BaronLetterMessages" (
                        "ThreadId", "BodyHtml", "Status", "IsInbound",
                        "TurnNumber", "Year", "Month", "Season",
                        "SeenByBaron", "SortOrder",
                        "CreatedAtUtc", "UpdatedAtUtc", "SentAtUtc"
                    )
                    SELECT
                        m.thread_id,
                        l."ReplyHtml",
                        'Sent',
                        TRUE,
                        COALESCE(l."ReplyTurnNumber", l."TurnNumber", 1),
                        COALESCE(l."ReplyYear", l."Year", 625),
                        COALESCE(l."ReplyMonth", l."Month", 1),
                        COALESCE(l."ReplySeason", l."Season", 'Winter'),
                        COALESCE(l."ReplySeenByBaron", TRUE),
                        COALESCE(l."SortOrder", 0) + 1,
                        COALESCE(l."UpdatedAtUtc", NOW()),
                        COALESCE(l."UpdatedAtUtc", NOW()),
                        COALESCE(l."UpdatedAtUtc", NOW())
                    FROM "BaronLetters" l
                    JOIN _thread_map m ON m.grp =
                        COALESCE(l."RelationId"::text, lower(trim(l."RecipientName")))
                        || '|' || lower(trim(COALESCE(l."Subject", '')))
                    WHERE l."GotReply" = TRUE
                      AND l."ReplyHtml" IS NOT NULL
                      AND TRIM(l."ReplyHtml") <> ''
                      AND TRIM(l."ReplyHtml") <> '<p></p>'
                      AND TRIM(l."ReplyHtml") <> '<p><br></p>';

                    DROP TABLE IF EXISTS "BaronLetters";
                END $$;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronLetterMessages";
                DROP TABLE IF EXISTS "BaronLetterThreads";
                """);
        }
    }
}
