using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260722200000_AddBaronPhpSources")]
    public partial class AddBaronPhpSources : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronPhpSources" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Source" text NOT NULL,
                    "Description" text NULL,
                    "Prestige" integer NOT NULL DEFAULT 0,
                    "Honor" integer NOT NULL DEFAULT 0,
                    "Fear" integer NOT NULL DEFAULT 0
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronPhpSources_BaronyId"
                    ON "BaronPhpSources" ("BaronyId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronPhpSources";
                """);
        }
    }
}
