using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260828120000_AddBaronyHallEvents")]
    public partial class AddBaronyHallEvents : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronyHallEvents" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Title" text NOT NULL DEFAULT '',
                    "Body" text NOT NULL DEFAULT '',
                    "TriggerKind" text NOT NULL DEFAULT 'Manual',
                    "Status" text NOT NULL DEFAULT 'Pending',
                    "TurnNumber" integer NOT NULL DEFAULT 0,
                    "IconPath" text NOT NULL DEFAULT 'icons/vertical-banner.svg',
                    "ResponseBody" text NOT NULL DEFAULT '',
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "AcknowledgedAtUtc" timestamp without time zone NULL
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronyHallEvents_BaronyId"
                    ON "BaronyHallEvents" ("BaronyId");

                CREATE INDEX IF NOT EXISTS "IX_BaronyHallEvents_BaronyId_Status"
                    ON "BaronyHallEvents" ("BaronyId", "Status");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronyHallEvents";
                """);
        }
    }
}
