using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260722210000_AddBaronArtifacts")]
    public partial class AddBaronArtifacts : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronArtifacts" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Name" text NOT NULL,
                    "Kind" text NOT NULL,
                    "Origin" text NOT NULL,
                    "Prestige" integer NOT NULL DEFAULT 0,
                    "Honor" integer NOT NULL DEFAULT 0,
                    "Fear" integer NOT NULL DEFAULT 0,
                    "SeatRoomId" integer NULL,
                    "Description" text NULL,
                    "SortOrder" integer NOT NULL DEFAULT 0
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronArtifacts_BaronyId"
                    ON "BaronArtifacts" ("BaronyId");

                CREATE INDEX IF NOT EXISTS "IX_BaronArtifacts_SeatRoomId"
                    ON "BaronArtifacts" ("SeatRoomId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronArtifacts";
                """);
        }
    }
}
