using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    /// <inheritdoc />
    public partial class AddBaronySeatSync : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronySeats" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Name" text NOT NULL DEFAULT 'Lord''s Seat',
                    "GridWidth" integer NOT NULL DEFAULT 12,
                    "GridHeight" integer NOT NULL DEFAULT 8
                );

                CREATE TABLE IF NOT EXISTS "SeatPurposeTemplates" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" text NOT NULL DEFAULT '',
                    "Description" text NOT NULL DEFAULT '',
                    "MinSizeCategory" text NOT NULL DEFAULT 'Small',
                    "WhoOccupies" text NOT NULL DEFAULT '',
                    "SleepCapacity" integer NOT NULL DEFAULT 0,
                    "AdditivePrestige" numeric NOT NULL DEFAULT 0,
                    "AdditiveJson" text NOT NULL DEFAULT '',
                    "PercentJson" text NOT NULL DEFAULT '',
                    "IsUniversal" boolean NOT NULL DEFAULT TRUE,
                    "BaronyId" integer NULL,
                    "SortOrder" integer NOT NULL DEFAULT 0
                );

                CREATE TABLE IF NOT EXISTS "SeatRooms" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "SeatId" integer NOT NULL,
                    "Name" text NOT NULL DEFAULT '',
                    "GridX" integer NOT NULL DEFAULT 0,
                    "GridY" integer NOT NULL DEFAULT 0,
                    "GridW" integer NOT NULL DEFAULT 1,
                    "GridH" integer NOT NULL DEFAULT 1,
                    "Material" text NOT NULL DEFAULT 'Stone',
                    "PrestigeMultiplier" numeric NOT NULL DEFAULT 1,
                    "Status" text NOT NULL DEFAULT 'Active',
                    "AdditiveJson" text NOT NULL DEFAULT '',
                    "PercentJson" text NOT NULL DEFAULT '',
                    "PurposeTemplateId" integer NULL,
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    CONSTRAINT "FK_SeatRooms_BaronySeats_SeatId"
                        FOREIGN KEY ("SeatId") REFERENCES "BaronySeats" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_SeatRooms_SeatId"
                    ON "SeatRooms" ("SeatId");

                CREATE TABLE IF NOT EXISTS "SeatRoomTraits" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RoomId" integer NOT NULL,
                    "Kind" text NOT NULL DEFAULT 'Advantage',
                    "Text" text NOT NULL DEFAULT '',
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    CONSTRAINT "FK_SeatRoomTraits_SeatRooms_RoomId"
                        FOREIGN KEY ("RoomId") REFERENCES "SeatRooms" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_SeatRoomTraits_RoomId"
                    ON "SeatRoomTraits" ("RoomId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "SeatRoomTraits";
                DROP TABLE IF EXISTS "SeatRooms";
                DROP TABLE IF EXISTS "SeatPurposeTemplates";
                DROP TABLE IF EXISTS "BaronySeats";
                """);
        }
    }
}
