using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260828150000_AddBaronyHallEventPhase3")]
    public partial class AddBaronyHallEventPhase3 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "BaronyHallEvents"
                    ADD COLUMN IF NOT EXISTS "PublishAtTurn" integer NULL,
                    ADD COLUMN IF NOT EXISTS "ConsequenceAdditiveJson" text NOT NULL DEFAULT '{}',
                    ADD COLUMN IF NOT EXISTS "ConsequencePercentJson" text NOT NULL DEFAULT '{}',
                    ADD COLUMN IF NOT EXISTS "ConsequenceEndTurn" integer NULL;

                CREATE TABLE IF NOT EXISTS "BaronyHallEventTemplates" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Name" text NOT NULL DEFAULT '',
                    "Title" text NOT NULL DEFAULT '',
                    "Body" text NOT NULL DEFAULT '',
                    "TriggerKind" text NOT NULL DEFAULT 'Manual',
                    "IconPath" text NOT NULL DEFAULT 'icons/vertical-banner.svg',
                    "ConsequenceAdditiveJson" text NOT NULL DEFAULT '{}',
                    "ConsequencePercentJson" text NOT NULL DEFAULT '{}',
                    "ConsequenceEndTurn" integer NULL,
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW()
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronyHallEventTemplates_BaronyId"
                    ON "BaronyHallEventTemplates" ("BaronyId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronyHallEventTemplates";

                ALTER TABLE "BaronyHallEvents"
                    DROP COLUMN IF EXISTS "PublishAtTurn",
                    DROP COLUMN IF EXISTS "ConsequenceAdditiveJson",
                    DROP COLUMN IF EXISTS "ConsequencePercentJson",
                    DROP COLUMN IF EXISTS "ConsequenceEndTurn";
                """);
        }
    }
}
