using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260720200000_BaronPurseSources")]
    public partial class BaronPurseSources : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronPurseSources" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "BaronyId" integer NOT NULL,
                    "Name" text NOT NULL,
                    "Description" text NULL,
                    "Amount" numeric NOT NULL DEFAULT 0,
                    CONSTRAINT "PK_BaronPurseSources" PRIMARY KEY ("Id")
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "BaronPurseSources";""");
        }
    }
}
