using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260831140000_AddBaronyDebts")]
    public partial class AddBaronyDebts : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronyDebts" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Direction" text NOT NULL DEFAULT 'Taken',
                    "CounterpartyName" text NOT NULL DEFAULT '',
                    "Notes" text NULL,
                    "Principal" numeric NOT NULL DEFAULT 0,
                    "PrincipalRemaining" numeric NOT NULL DEFAULT 0,
                    "InterestRatePercent" numeric NOT NULL DEFAULT 0,
                    "PaymentPerTurn" numeric NOT NULL DEFAULT 0,
                    "StartTurn" integer NOT NULL DEFAULT 1,
                    "IsActive" boolean NOT NULL DEFAULT TRUE
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronyDebts_BaronyId"
                    ON "BaronyDebts" ("BaronyId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronyDebts";
                """);
        }
    }
}
