using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260722230000_AddBaronLetters")]
    public partial class AddBaronLetters : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronLetters" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "RelationId" integer NULL,
                    "RecipientName" text NOT NULL,
                    "RecipientTitle" text NULL,
                    "RecipientCategory" text NULL,
                    "Subject" text NULL,
                    "BodyHtml" text NOT NULL DEFAULT '',
                    "Status" text NOT NULL,
                    "ReplyRegion" text NOT NULL,
                    "TurnNumber" integer NOT NULL DEFAULT 1,
                    "Year" integer NOT NULL DEFAULT 625,
                    "Month" integer NOT NULL DEFAULT 1,
                    "Season" text NOT NULL DEFAULT 'Winter',
                    "GotReply" boolean NOT NULL DEFAULT FALSE,
                    "ReplyTurnNumber" integer NULL,
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "SentAtUtc" timestamp without time zone NULL
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronLetters_BaronyId"
                    ON "BaronLetters" ("BaronyId");

                CREATE INDEX IF NOT EXISTS "IX_BaronLetters_RelationId"
                    ON "BaronLetters" ("RelationId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronLetters";
                """);
        }
    }
}
