using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260825150000_AddBaronyHallAdventures")]
    public partial class AddBaronyHallAdventures : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronyHallAdventures" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Name" text NOT NULL DEFAULT '',
                    "IconPath" text NOT NULL DEFAULT 'icons/bookmarklet.svg',
                    "LinkUrl" text NOT NULL DEFAULT '',
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW()
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronyHallAdventures_BaronyId"
                    ON "BaronyHallAdventures" ("BaronyId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronyHallAdventures";
                """);
        }
    }
}
