using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260910120000_AddBaronyLog")]
    public partial class AddBaronyLog : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronyLogEntries" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "BaronyId" integer NOT NULL,
                    "TurnNumber" integer NOT NULL,
                    "Year" integer NOT NULL,
                    "Month" integer NOT NULL,
                    "Season" text NOT NULL DEFAULT '',
                    "Category" text NOT NULL DEFAULT '',
                    "Actor" text NOT NULL DEFAULT '',
                    "ActorRole" text NOT NULL DEFAULT '',
                    "Summary" character varying(400) NOT NULL DEFAULT '',
                    "Details" text NULL,
                    "EntityType" text NULL,
                    "EntityId" integer NULL,
                    "IsImportant" boolean NOT NULL DEFAULT FALSE,
                    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
                    CONSTRAINT "PK_BaronyLogEntries" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronyLogEntries_Barony_Turn"
                    ON "BaronyLogEntries" ("BaronyId", "TurnNumber", "CreatedAtUtc");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronyLogEntries";
                """);
        }
    }
}
