using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260825220000_AddBaronQaThreads")]
    public partial class AddBaronQaThreads : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronQaThreads" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Title" text NOT NULL DEFAULT '',
                    "CreatedTurn" integer NOT NULL DEFAULT 0,
                    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW()
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronQaThreads_BaronyId"
                    ON "BaronQaThreads" ("BaronyId");

                CREATE TABLE IF NOT EXISTS "BaronQaMessages" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ThreadId" integer NOT NULL,
                    "Body" text NOT NULL DEFAULT '',
                    "IsFromGm" boolean NOT NULL DEFAULT FALSE,
                    "SpeakerName" text NULL,
                    "TurnNumber" integer NOT NULL DEFAULT 0,
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "SeenByBaron" boolean NOT NULL DEFAULT TRUE,
                    "SeenByGm" boolean NOT NULL DEFAULT TRUE,
                    CONSTRAINT "FK_BaronQaMessages_BaronQaThreads_ThreadId"
                        FOREIGN KEY ("ThreadId") REFERENCES "BaronQaThreads" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronQaMessages_ThreadId"
                    ON "BaronQaMessages" ("ThreadId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronQaMessages";
                DROP TABLE IF EXISTS "BaronQaThreads";
                """);
        }
    }
}
