using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260720190000_BaronyResourceStocksAndSources")]
    public partial class BaronyResourceStocksAndSources : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF NOT EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'Baronies' AND column_name = 'ResourceStocksJson') THEN
                    ALTER TABLE "Baronies" ADD "ResourceStocksJson" text NOT NULL DEFAULT '{}';
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF NOT EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'Baronies' AND column_name = 'PreviousTurnIncomeJson') THEN
                    ALTER TABLE "Baronies" ADD "PreviousTurnIncomeJson" text NOT NULL DEFAULT '{}';
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronyResourceSources" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "BaronyId" integer NOT NULL,
                    "Name" text NOT NULL,
                    "Description" text NULL,
                    "AdditiveJson" text NOT NULL DEFAULT '{}',
                    CONSTRAINT "PK_BaronyResourceSources" PRIMARY KEY ("Id")
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "BaronyResourceSources";""");

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'Baronies' AND column_name = 'PreviousTurnIncomeJson') THEN
                    ALTER TABLE "Baronies" DROP COLUMN "PreviousTurnIncomeJson";
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'Baronies' AND column_name = 'ResourceStocksJson') THEN
                    ALTER TABLE "Baronies" DROP COLUMN "ResourceStocksJson";
                  END IF;
                END $$;
                """);
        }
    }
}
