using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DA_DataAccess.Migrations
{
    /// <inheritdoc />
    public partial class BaronySettlementPopulationAndAdvisors : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'TerrainImprovements' AND column_name = 'Society') THEN
                    ALTER TABLE "TerrainImprovements" RENAME COLUMN "Society" TO "Population";
                  ELSIF NOT EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'TerrainImprovements' AND column_name = 'Population') THEN
                    ALTER TABLE "TerrainImprovements" ADD "Population" integer NOT NULL DEFAULT 0;
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'BaronyBuildings' AND column_name = 'Society') THEN
                    ALTER TABLE "BaronyBuildings" DROP COLUMN "Society";
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF NOT EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'TerrainImprovements' AND column_name = 'HasPalisade') THEN
                    ALTER TABLE "TerrainImprovements" ADD "HasPalisade" boolean NOT NULL DEFAULT false;
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF NOT EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'SocialGroupRelations' AND column_name = 'TaxPercent') THEN
                    ALTER TABLE "SocialGroupRelations" ADD "TaxPercent" integer NULL;
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF NOT EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'Advisors' AND column_name = 'AvailableAdvisorId') THEN
                    ALTER TABLE "Advisors" ADD "AvailableAdvisorId" integer NULL;
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "AvailableAdvisors" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "BaronyId" integer NOT NULL,
                    "Name" text NOT NULL,
                    "Description" text NULL,
                    "SkillsJson" text NOT NULL,
                    CONSTRAINT "PK_AvailableAdvisors" PRIMARY KEY ("Id")
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AvailableAdvisors");

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'Advisors' AND column_name = 'AvailableAdvisorId') THEN
                    ALTER TABLE "Advisors" DROP COLUMN "AvailableAdvisorId";
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'SocialGroupRelations' AND column_name = 'TaxPercent') THEN
                    ALTER TABLE "SocialGroupRelations" DROP COLUMN "TaxPercent";
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'TerrainImprovements' AND column_name = 'HasPalisade') THEN
                    ALTER TABLE "TerrainImprovements" DROP COLUMN "HasPalisade";
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'TerrainImprovements' AND column_name = 'Population') THEN
                    ALTER TABLE "TerrainImprovements" RENAME COLUMN "Population" TO "Society";
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                  IF NOT EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_name = 'BaronyBuildings' AND column_name = 'Society') THEN
                    ALTER TABLE "BaronyBuildings" ADD "Society" integer NOT NULL DEFAULT 0;
                  END IF;
                END $$;
                """);
        }
    }
}
