using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260722220000_AddBaronTime")]
    public partial class AddBaronTime : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronTimeModifiers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Source" text NOT NULL,
                    "Percent" numeric NOT NULL DEFAULT 0,
                    "Description" text NULL,
                    "SortOrder" integer NOT NULL DEFAULT 0
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronTimeModifiers_BaronyId"
                    ON "BaronTimeModifiers" ("BaronyId");

                CREATE TABLE IF NOT EXISTS "BaronTimeActions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Name" text NOT NULL,
                    "Kind" text NOT NULL,
                    "CostJc" integer NOT NULL DEFAULT 0,
                    "Description" text NULL,
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    "IsSystem" boolean NOT NULL DEFAULT FALSE
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronTimeActions_BaronyId"
                    ON "BaronTimeActions" ("BaronyId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronTimeActions";
                DROP TABLE IF EXISTS "BaronTimeModifiers";
                """);
        }
    }
}
