using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260729190000_AddBaronAudiences")]
    public partial class AddBaronAudiences : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronAudiences" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Title" text NOT NULL DEFAULT '',
                    "PetitionerName" text NOT NULL DEFAULT '',
                    "Status" text NOT NULL DEFAULT 'Scheduled',
                    "TurnNumber" integer NOT NULL DEFAULT 1,
                    "ContinuedFromAudienceId" integer NULL,
                    "GmSummary" text NOT NULL DEFAULT '',
                    "OutcomeNotes" text NOT NULL DEFAULT '',
                    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "ClosedAtUtc" timestamp without time zone NULL
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronAudiences_BaronyId"
                    ON "BaronAudiences" ("BaronyId");

                CREATE INDEX IF NOT EXISTS "IX_BaronAudiences_BaronyId_TurnNumber"
                    ON "BaronAudiences" ("BaronyId", "TurnNumber");

                CREATE INDEX IF NOT EXISTS "IX_BaronAudiences_ContinuedFromAudienceId"
                    ON "BaronAudiences" ("ContinuedFromAudienceId");

                CREATE TABLE IF NOT EXISTS "BaronAudienceExchanges" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "AudienceId" integer NOT NULL,
                    "Body" text NOT NULL DEFAULT '',
                    "IsFromPetitioner" boolean NOT NULL DEFAULT TRUE,
                    "TurnNumber" integer NOT NULL DEFAULT 1,
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT "FK_BaronAudienceExchanges_Audiences"
                        FOREIGN KEY ("AudienceId") REFERENCES "BaronAudiences" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronAudienceExchanges_AudienceId"
                    ON "BaronAudienceExchanges" ("AudienceId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronAudienceExchanges";
                DROP TABLE IF EXISTS "BaronAudiences";
                """);
        }
    }
}
