using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(DA_DataAccess.Data.ApplicationDbContext))]
    [Migration("20260721200000_AddBaronyRelations")]
    public partial class AddBaronyRelations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BaronyRelations" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BaronyId" integer NOT NULL,
                    "Category" text NOT NULL DEFAULT 'Friends, acquaintances and enemies',
                    "GroupName" text NOT NULL DEFAULT '',
                    "Name" text NOT NULL DEFAULT '',
                    "Title" text NOT NULL DEFAULT '',
                    "Age" integer NULL,
                    "Description" text NOT NULL DEFAULT '',
                    "TroopCount" integer NOT NULL DEFAULT 0,
                    "RelationDescription" text NOT NULL DEFAULT '',
                    "Notes" text NULL,
                    "SortOrder" integer NOT NULL DEFAULT 0
                );

                CREATE TABLE IF NOT EXISTS "BaronyRelationModifiers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RelationId" integer NOT NULL,
                    "Description" text NOT NULL DEFAULT '',
                    "Value" integer NOT NULL DEFAULT 0,
                    "SortOrder" integer NOT NULL DEFAULT 0,
                    CONSTRAINT "FK_BaronyRelationModifiers_BaronyRelations_RelationId"
                        FOREIGN KEY ("RelationId") REFERENCES "BaronyRelations" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_BaronyRelations_BaronyId"
                    ON "BaronyRelations" ("BaronyId");

                CREATE INDEX IF NOT EXISTS "IX_BaronyRelationModifiers_RelationId"
                    ON "BaronyRelationModifiers" ("RelationId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BaronyRelationModifiers";
                DROP TABLE IF EXISTS "BaronyRelations";
                """);
        }
    }
}
