using DA_DataAccess.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DA_DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722150000_AddSeatFloorsAndTiles")]
    public partial class AddSeatFloorsAndTiles : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "BaronySeats"
                ADD COLUMN IF NOT EXISTS "ActiveLevelsJson" text NOT NULL DEFAULT '[0]';

                ALTER TABLE "SeatRooms"
                ADD COLUMN IF NOT EXISTS "Level" integer NOT NULL DEFAULT 0;

                CREATE TABLE IF NOT EXISTS "SeatTiles" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "SeatId" integer NOT NULL,
                    "Level" integer NOT NULL DEFAULT 0,
                    "X" integer NOT NULL DEFAULT 0,
                    "Y" integer NOT NULL DEFAULT 0,
                    "Kind" text NOT NULL DEFAULT 'Ground',
                    CONSTRAINT "FK_SeatTiles_BaronySeats_SeatId"
                        FOREIGN KEY ("SeatId") REFERENCES "BaronySeats" ("Id") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SeatTiles_SeatId_Level_X_Y"
                    ON "SeatTiles" ("SeatId", "Level", "X", "Y");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "SeatTiles";
                ALTER TABLE "SeatRooms" DROP COLUMN IF EXISTS "Level";
                ALTER TABLE "BaronySeats" DROP COLUMN IF EXISTS "ActiveLevelsJson";
                """);
        }
    }
}
