/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_ENGINEREMOTESTART_ERSRESPONSE_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_ENGINEREMOTESTART_ERSRESPONSE_PB_H_INCLUDED
#include <pb.h>
#include "entities/common/ResponseStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* OID {1.3.6.1.4.1.37916.3.6.20.0.0.3} */
typedef struct _remote_control_ERSResponse { 
    bool has_response_status;
    common_ResponseStatus response_status; 
} remote_control_ERSResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_ERSResponse_init_default  {false, common_ResponseStatus_init_default}
#define remote_control_ERSResponse_init_zero     {false, common_ResponseStatus_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_ERSResponse_response_status_tag 1

/* Struct field encoding specification for nanopb */
#define remote_control_ERSResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  response_status,   1)
#define remote_control_ERSResponse_CALLBACK NULL
#define remote_control_ERSResponse_DEFAULT NULL
#define remote_control_ERSResponse_response_status_MSGTYPE common_ResponseStatus

extern const pb_msgdesc_t remote_control_ERSResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_ERSResponse_fields &remote_control_ERSResponse_msg

/* Maximum encoded size of messages (where known) */
#if defined(common_ResponseStatus_size)
#define remote_control_ERSResponse_size          (6 + common_ResponseStatus_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
