/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_ENGINEREMOTESTART_ERSREQUEST_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_ENGINEREMOTESTART_ERSREQUEST_PB_H_INCLUDED
#include <pb.h>
#include "entities/common/CommonTypes.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _remote_control_ErsSeatWheelHeatType { 
    remote_control_ErsSeatWheelHeatType_ERS_STATUS_OFF = 0, 
    remote_control_ErsSeatWheelHeatType_ERS_STATUS_AUTO = 1 
} remote_control_ErsSeatWheelHeatType;

/* Struct definitions */
/* OID {1.3.6.1.4.1.37916.3.6.20.0.0.2} */
typedef struct _remote_control_ERSRequest { 
    common_CommonTypes_OnOffNoReq type; 
    int32_t run_time; 
    remote_control_ErsSeatWheelHeatType left_front_seat_heat; 
    remote_control_ErsSeatWheelHeatType right_front_seat_heat; 
    remote_control_ErsSeatWheelHeatType steering_wheel_heat; 
} remote_control_ERSRequest;


/* Helper constants for enums */
#define _remote_control_ErsSeatWheelHeatType_MIN remote_control_ErsSeatWheelHeatType_ERS_STATUS_OFF
#define _remote_control_ErsSeatWheelHeatType_MAX remote_control_ErsSeatWheelHeatType_ERS_STATUS_AUTO
#define _remote_control_ErsSeatWheelHeatType_ARRAYSIZE ((remote_control_ErsSeatWheelHeatType)(remote_control_ErsSeatWheelHeatType_ERS_STATUS_AUTO+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_ERSRequest_init_default   {_common_CommonTypes_OnOffNoReq_MIN, 0, _remote_control_ErsSeatWheelHeatType_MIN, _remote_control_ErsSeatWheelHeatType_MIN, _remote_control_ErsSeatWheelHeatType_MIN}
#define remote_control_ERSRequest_init_zero      {_common_CommonTypes_OnOffNoReq_MIN, 0, _remote_control_ErsSeatWheelHeatType_MIN, _remote_control_ErsSeatWheelHeatType_MIN, _remote_control_ErsSeatWheelHeatType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_ERSRequest_type_tag       1
#define remote_control_ERSRequest_run_time_tag   2
#define remote_control_ERSRequest_left_front_seat_heat_tag 3
#define remote_control_ERSRequest_right_front_seat_heat_tag 4
#define remote_control_ERSRequest_steering_wheel_heat_tag 5

/* Struct field encoding specification for nanopb */
#define remote_control_ERSRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    run_time,          2) \
X(a, STATIC,   SINGULAR, UENUM,    left_front_seat_heat,   3) \
X(a, STATIC,   SINGULAR, UENUM,    right_front_seat_heat,   4) \
X(a, STATIC,   SINGULAR, UENUM,    steering_wheel_heat,   5)
#define remote_control_ERSRequest_CALLBACK NULL
#define remote_control_ERSRequest_DEFAULT NULL

extern const pb_msgdesc_t remote_control_ERSRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_ERSRequest_fields &remote_control_ERSRequest_msg

/* Maximum encoded size of messages (where known) */
#define remote_control_ERSRequest_size           19

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
