/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_ENGINEREMOTESTART_ERSSTATUSREQUEST_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_ENGINEREMOTESTART_ERSSTATUSREQUEST_PB_H_INCLUDED
#include <pb.h>
#include "entities/common/CommonTypes.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* OID {1.3.6.1.4.1.37916.3.6.20.0.1.2} */
typedef struct _remote_control_ERSStatusRequest { 
    char dummy_field;
} remote_control_ERSStatusRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_ERSStatusRequest_init_default {0}
#define remote_control_ERSStatusRequest_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
#define remote_control_ERSStatusRequest_FIELDLIST(X, a) \

#define remote_control_ERSStatusRequest_CALLBACK NULL
#define remote_control_ERSStatusRequest_DEFAULT NULL

extern const pb_msgdesc_t remote_control_ERSStatusRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_ERSStatusRequest_fields &remote_control_ERSStatusRequest_msg

/* Maximum encoded size of messages (where known) */
#define remote_control_ERSStatusRequest_size     0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
