/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_ENGINEREMOTESTART_ERSSTATUSRESPONSE_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_ENGINEREMOTESTART_ERSSTATUSRESPONSE_PB_H_INCLUDED
#include <pb.h>
#include "entities/common/ResponseStatus.pb.h"
#include "entities/engineremotestart/ErsStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* OID {1.3.6.1.4.1.37916.3.6.20.0.1.3} */
typedef struct _remote_control_ERSStatusResponse { 
    bool has_response_status;
    common_ResponseStatus response_status; /* required */
    bool has_ers_status;
    status_ErsStatus ers_status; 
} remote_control_ERSStatusResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_ERSStatusResponse_init_default {false, common_ResponseStatus_init_default, false, status_ErsStatus_init_default}
#define remote_control_ERSStatusResponse_init_zero {false, common_ResponseStatus_init_zero, false, status_ErsStatus_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_ERSStatusResponse_response_status_tag 1
#define remote_control_ERSStatusResponse_ers_status_tag 2

/* Struct field encoding specification for nanopb */
#define remote_control_ERSStatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  response_status,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ers_status,        2)
#define remote_control_ERSStatusResponse_CALLBACK NULL
#define remote_control_ERSStatusResponse_DEFAULT NULL
#define remote_control_ERSStatusResponse_response_status_MSGTYPE common_ResponseStatus
#define remote_control_ERSStatusResponse_ers_status_MSGTYPE status_ErsStatus

extern const pb_msgdesc_t remote_control_ERSStatusResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_ERSStatusResponse_fields &remote_control_ERSStatusResponse_msg

/* Maximum encoded size of messages (where known) */
#if defined(common_ResponseStatus_size)
#define remote_control_ERSStatusResponse_size    (12 + common_ResponseStatus_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
