/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_REMOTE_CONTROL_MESSAGES_ENGINEREMOTESTART_ERSSTATUSUPDATE_PB_H_INCLUDED
#define PB_REMOTE_CONTROL_MESSAGES_ENGINEREMOTESTART_ERSSTATUSUPDATE_PB_H_INCLUDED
#include <pb.h>
#include "entities/engineremotestart/ErsStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* OID {1.3.6.1.4.1.37916.3.6.20.0.1.1} */
typedef struct _remote_control_ERSStatusUpdate { 
    bool has_ers_status;
    status_ErsStatus ers_status; 
} remote_control_ERSStatusUpdate;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define remote_control_ERSStatusUpdate_init_default {false, status_ErsStatus_init_default}
#define remote_control_ERSStatusUpdate_init_zero {false, status_ErsStatus_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define remote_control_ERSStatusUpdate_ers_status_tag 1

/* Struct field encoding specification for nanopb */
#define remote_control_ERSStatusUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ers_status,        1)
#define remote_control_ERSStatusUpdate_CALLBACK NULL
#define remote_control_ERSStatusUpdate_DEFAULT NULL
#define remote_control_ERSStatusUpdate_ers_status_MSGTYPE status_ErsStatus

extern const pb_msgdesc_t remote_control_ERSStatusUpdate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_control_ERSStatusUpdate_fields &remote_control_ERSStatusUpdate_msg

/* Maximum encoded size of messages (where known) */
#define remote_control_ERSStatusUpdate_size      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
